### ISSUE TITLE
ConnectionPool should not lowercase all hostnames

### ISSUE THREAD

**Issue by lslebodn** [urllib3/urllib3#1267]
This is kind of follow up issue to:
* https://github.com/shazow/urllib3/issues/1080
* https://github.com/requests/requests/pull/3713
* https://github.com/kennethreitz/requests/pull/3738

Even though that #1080 was fixed in #1089 there was another commit which introduced a small regression 9ff2ccc9a9265436889a14726e9b010ae91b0e68. (I now it is there since 1.20 but I didn't have a time to investigate it for long time.

Here is a reproducer with python requests:
```bash
sh$ cat test.py
import socket
import requests

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.connection import HTTPConnection
from requests.packages.urllib3.connectionpool import HTTPConnectionPool
from requests.compat import quote, unquote, urlparse


class HTTPUnixConnection(HTTPConnection):
    def __init__(self, host, timeout=60, **kwargs):
        super(HTTPUnixConnection, self).__init__('localhost')
        self.unix_socket = host
        self.timeout = timeout
        self.sock = None

    def connect(self):
        sock = socket.socket(family=socket.AF_UNIX)
        sock.settimeout(self.timeout)
        sock.connect(self.unix_socket)
        self.sock = sock


class HTTPUnixConnectionPool(HTTPConnectionPool):
    scheme = 'http+unix'
    ConnectionCls = HTTPUnixConnection


class HTTPUnixAdapter(HTTPAdapter):
    def get_connection(self, url, proxies=None):
        # proxies, silently ignored
        path = unquote(urlparse(url).netloc)
        return HTTPUnixConnectionPool(path)


def main():
    sock_path = '/tmp/FILE.sock'
    content_type = 'application/octet-stream'

    session = requests.Session()
    session.mount('http+unix://', HTTPUnixAdapter())
    headers = {'headers': {'Content-Type': content_type}}
    test_url = 'http+unix://' + quote(sock_path, safe='') + '/foo'

    result = session.get(test_url, **headers)
    assert result.text == 'bar'
    assert result.status_code == 200
    print(result.status_code)
    print(result.text)

if __name__ == "__main__":
    main()

sh$ printf 'HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: 3\r\n\r\nbar' > /tmp/http_response
sh$ rm -f /tmp/FILE.sock
sh$ nc --unixsock --listen /tmp/FILE.sock < /tmp/http_response

# in different terminal run test
sh$ python test.py
```

Actual results:
```
Traceback (most recent call last):
  File "pok.py", line 52, in <module>
    main()
  File "pok.py", line 45, in main
    result = session.get(test_url, **headers)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

Expected results:
```
200
bar
```

**Comment by lslebodn** [comment]
Following diff fixes issue for me and should not break 9ff2ccc9a9265436889a14726e9b010ae91b0e68
```
diff --git a/urllib3/connectionpool.py b/urllib3/connectionpool.py
index 85be0b4..2461f2d 100644
--- a/urllib3/connectionpool.py
+++ b/urllib3/connectionpool.py
@@ -68,7 +68,7 @@ class ConnectionPool(object):
         if not host:
             raise LocationValueError("No host specified.")
 
-        self.host = _ipv6_host(host).lower()
+        self.host = _ipv6_host(host)
         self._proxy_host = host.lower()
         self.port = port
 
@@ -434,7 +434,7 @@ class HTTPConnectionPool(ConnectionPool, RequestMethods):
         # TODO: Add optional support for socket.gethostbyname checking.
         scheme, host, port = get_host(url)
 
-        host = _ipv6_host(host).lower()
+        host = _ipv6_host(host)
 
         # Use explicit default port for comparison when none is given
         if self.port and not port:
@@ -901,5 +901,5 @@ def _ipv6_host(host):
     # Also if an IPv6 address literal has a zone identifier, the
     # percent sign might be URIencoded, convert it back into ASCII
     if host.startswith('[') and host.endswith(']'):
-        host = host.replace('%25', '%').strip('[]')
+        host = host.lower().replace('%25', '%').strip('[]')
     return host
```

I am just not sure how to reasonably write a test for it. Because there could be uni test for this but
it would be good to also rewrite a test from description info pure python in https://github.com/requests/requests to cover use case there.

**Comment by Lukasa** [comment]
A straightforward unit test is fine for now. 🙂

**Comment by lslebodn** [comment]
@Lukasa May I know when do you plan to release next upstream version.
I would like to know how to prioritize this bug in my TODO list :-)

**Comment by Lukasa** [comment]
Not for a little while: I will be travelling for work for the next few weeks so I will be aiming not to release during that time.

**Comment by sigmavirus24** [comment]
I started writing a long response to this about how hosts aren't case-sensitive and then I realized how truly tiny the patch you've provided is (and how it's technically better) and am fully on board. Either way @lslebodn I would suggest you submit a patch for this sooner rather than later so we can help you write the test and get it into the next release.

**Comment by lslebodn** [comment]
@sigmavirus24 the patch in https://github.com/shazow/urllib3/issues/1267#issuecomment-328588075 is not correct. I have different one but I need to find a time to write unit test :-)
