### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'close'

### ISSUE THREAD

**Issue by IcyNoctiluca** [urllib3/urllib3#1381]
I get the following error very infrequently when sending network requests:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 297, in read
    data = self._fp.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 185 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 185 more expected)', IncompleteRead(0 bytes read, 185 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "btcStpMine.py", line 24, in <module>
    response = http.request('GET', addr,)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 69, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 572, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 375, in from_httplib
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 137, in __init__
    self._body = self.read(decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 256, in _error_catcher
    self._connection.close()
AttributeError: 'bool' object has no attribute 'close'
```

Where the underlying code involving the library simply is:

```
http = urllib3.PoolManager()
response = http.request('GET', addr)
data = json.loads(response.data.decode("utf-8"))
```

In a while loop (paused by a second each iteration), this executed perfectly 15128 times and then threw the above error.

Using Python 3.5.2 and Urllib3 version 1.13.1 on Ubuntu 1604.

Any idea?

Thanks

**Comment by SethMichaelLarson** [comment]
I'm going to close this as resolved. :) If this problem arises again in the latest version of urllib3 feel free to reopen.
