### ISSUE TITLE
problems testing with pluggy 0.8.0

### ISSUE THREAD

**Issue by caboteria** [urllib3/urllib3#1455]
Pluggy 0.8.0 was released today and it is causing my tox runs to fail.  I get:

```
$ tox -e py36
GLOB sdist-make: /home/tcabot/Code/urllib3/setup.py
py36 inst-nodeps: /home/tcabot/Code/urllib3/.tox/dist/urllib3-dev.zip
py36 installed: /home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,  import imp,asn1crypto==0.24.0,astroid==2.0.4,atomicwrites==1.2.1,attrs==18.2.0,certifi==2018.10.15,cffi==1.11.5,chardet==3.0.4,coverage==4.5.1,cryptography==2.3.1,gcp-devrel-py-tools==0.0.15,idna==2.7,ipaddress==1.0.22,isort==4.3.4,lazy-object-proxy==1.3.1,mccabe==0.6.1,mock==2.0.0,more-itertools==4.3.0,packaging==18.0,pbr==4.3.0,pkginfo==1.4.2,pluggy==0.8.0,py==1.7.0,pycparser==2.19,pylint==2.1.1,pyOpenSSL==18.0.0,pyparsing==2.2.2,PySocks==1.6.8,pytest==3.6.4,pytest-timeout==1.3.1,requests==2.19.1,requests-toolbelt==0.8.0,retrying==1.3.3,six==1.11.0,tornado==5.0.2,tox==2.9.1,tqdm==4.27.0,twine==1.11.0,typed-ast==1.1.0,urllib3===dev,virtualenv==16.0.0,wrapt==1.10.11
py36 runtests: PYTHONHASHSEED='4079776103'
py36 runtests: commands[0] | pip --version
/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
pip 18.1 from /home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pip (python 3.6)
py36 runtests: commands[1] | python --version
Python 3.6.6
py36 runtests: commands[2] | python -c import struct; print(struct.calcsize('P') * 8)
64
py36 runtests: commands[3] | coverage run --parallel-mode -m pytest -r sx test
/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2331, in load
    self.require(*args, **kwargs)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2354, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pluggy 0.8.0 (/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages), Requirement.parse('pluggy<0.8,>=0.5'), {'pytest'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pytest.py", line 67, in <module>
    raise SystemExit(pytest.main())
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 180, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 612, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 777, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/_pytest/config/__init__.py", line 729, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages/pluggy/manager.py", line 273, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'timeout' could not be loaded: (pluggy 0.8.0 (/home/tcabot/Code/urllib3/.tox/py36/lib/python3.6/site-packages), Requirement.parse('pluggy<0.8,>=0.5'), {'pytest'})!
Coverage.py warning: Module urllib3 was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
ERROR: InvocationError: '/home/tcabot/Code/urllib3/.tox/py36/bin/coverage run --parallel-mode -m pytest -r sx test'
____________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
ERROR:   py36: commands failed
```

Looks like maybe pluggy 0.8.0 conflicts with timeout somehow?  If I pin pluggy<0.8.0 in dev-requirements.txt (and delete my .tox directory) then pluggy 0.7.1 gets installed and the tests proceed.

**Comment by caboteria** [comment]
The travis builds are now failing with the same error that I got: https://travis-ci.org/urllib3/urllib3/jobs/442302590

**Comment by SethMichaelLarson** [comment]
Maybe a regression on 0.7.1, would require some more investigation to see what changed.

**Comment by caboteria** [comment]
Looking a little deeper, urllib3's dev-requirements.txt requires pytest==3.6.4 and pytest 3.6.4's setup.py requires pluggy>=0.5,<0.8.  The most current version of pytest, 3.8.2, requires pluggy>=0.7 which would work with the new pluggy.  So you could either add pluggy<0.8 or allow a newer pytest in urllib3's dev-requirements.txt.

I tried pytest=3.8.2 and it worked at least as well as 3.6.4 for me but I don't have the full suite passing  yet.

**Comment by theacodes** [comment]
I'm +1 on updating pytest.

**Comment by caboteria** [comment]
PR 1457 fixes the build, at least for me: https://travis-ci.org/Affectiva/urllib3/builds/442374641
