### ISSUE TITLE
HTTP CONNECT request sent in different packets while using an HTTPS Proxy 

### ISSUE THREAD

**Issue by brad-anton** [urllib3/urllib3#1491]
*Note* At the [request of the requests team](https://github.com/requests/requests/issues/4884), I've opened a ticket here. 

When using an HTTPS proxy, HTTP headers (and other parts of the request) are sent at different times then the initial HTTP `CONNECT` method, causing _some_ proxy services to abort the connection. 

## Expected Result

The entire HTTP request should be sent in the same packet as the `CONNECT` method. 

## Actual Result

HTTP Headers and trailing `\r\n` are sent at a different time. 

You can see this in the Wireshark Capture:

First Packet contains the HTTP CONNECT (from [here](https://github.com/python/cpython/blob/master/Lib/http/client.py#L895-L898)) 

![screen shot 2018-11-28 at 15 55 17](https://user-images.githubusercontent.com/1035793/49182352-10bf1600-f328-11e8-8f8b-8b78694ad125.png)

Second packet shows the left over `\r\n` (from [here](https://github.com/python/cpython/blob/master/Lib/http/client.py#L903))

![screen shot 2018-11-28 at 15 56 05](https://user-images.githubusercontent.com/1035793/49182338-06048100-f328-11e8-988b-b3268ec1d0e7.png)

This results in _some_ proxy servers aborting the connection.

## Reproduction Steps

```
>>> import requests
>>> proxies = { 'https': 'https://someproxy:443' }
>>> requests.get('https://www.google.com', proxies=proxies)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error(54, 'Connection reset by peer')))
```

## System Information
```
$ python -V
Python 2.7.11
```
(Same behavior on Python 3)

MacOSX

## Work Around
The following work around sends the entire HTTP `CONNECT` request at the same time:

https://gist.github.com/brad-anton/ff517025a86754793b680b3c5cfc9797

**Comment by SethMichaelLarson** [comment]
Would you be willing to submit a PR for this change?

**Comment by brad-anton** [comment]
@SethMichaelLarson Do you think this is by design in httplib?

**Comment by SethMichaelLarson** [comment]
I don't think so, probably only there due to not having to allocate a buffer for all headers instead just send them as they're encoded.  There (should be) no difference between sending all at once versus sending headers one by one but if some proxies don't implement that properly it'd be nice to support them as well.

There shouldn't be an issue of buffering too much data as I can't imagine the number of headers getting to be where that is a problem. And if there is or this change breaks others we'll hear about it and re-evaluate this decision. :)

**Comment by brad-anton** [comment]
One other thing @SethMichaelLarson - wouldnt the fix be in here rather then in urllib?
* https://github.com/python/cpython/blob/master/Lib/http/client.py#L895-L898

**Comment by sethmlarson** [comment]
@gleopoldo There's no patch open for this issue yet but you could be the first to provide one!

**Comment by gleopoldo** [comment]
Okay. I thought that they might be related, but I'm going to open a separated one for this, so. Tks!

**Comment by MinasA1** [comment]
Sorry but above @brad-anton have provided you with a workaround and also have pointed out the issue and it's solution. 

https://gist.github.com/brad-anton/ff517025a86754793b680b3c5cfc9797

**Comment by gleopoldo** [comment]
Didn't saw above. Tks @MinasA1. 
Also, deeping into my problem, maybe it's related to the proxy itself, and not with urllib. I'm going to check out it's configurations to find the root cause for that one...
