### ISSUE TITLE
run-time issue while running fbchat via Java/Jython

### ISSUE THREAD

**Issue by navneethnarendra** [urllib3/urllib3#1499]
import java.util.Properties;
import javax.script.ScriptException;
import org.python.util.PythonInterpreter;

public class PythonInJava {

	@SuppressWarnings("resource")
	public static void main(final String[] args) throws ScriptException {
		System.setProperty("python.cachedir.skip", "true");
		Properties p = new Properties();
		p.setProperty("python.path",
				"/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar");
		p.setProperty("python.home",
				"/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar");
		p.setProperty("python.prefix",
				"/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar");
		PythonInterpreter.initialize(System.getProperties(), p, new String[] {});

		PythonInterpreter interpreter = new PythonInterpreter();

		interpreter.exec("import sys");
		interpreter.exec("sys.path.append(\"/Users/<user>/fbchat\")");
		interpreter.exec("sys.path.append(\"/usr/local/lib/python2.7/site-packages\")");
		interpreter.exec("from fbchat import Client");
		interpreter.exec("from fbchat.models import *");
		interpreter.exec("client = Client('<uid>', '<pwd>')");
	}

}

when running the above Java app, here is the stack trace:

Logging in <uid>…
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/<user>/fbchat/fbchat/client.py", line 81, in __init__
    self.login(email, password, max_tries)
  File "/Users/<user>/fbchat/fbchat/client.py", line 386, in login
    login_successful, login_url = self._login()
  File "/Users/<user>/fbchat/fbchat/client.py", line 247, in _login
    soup = bs(self._get(self.req_url.MOBILE).text, "html.parser")
  File "/Users/<user>/fbchat/fbchat/client.py", line 116, in _get
    r = self._session.get(url, headers=self._header, params=payload, timeout=timeout, verify=self.ssl_verify)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/httplib.py", line 1042, in request
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/httplib.py", line 1082, in _send_request
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/httplib.py", line 1038, in endheaders
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/httplib.py", line 882, in _send_output
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/httplib.py", line 858, in send
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/ssl.py", line 719, in sendall
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/_socket.py", line 1441, in meth
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/_socket.py", line 382, in handle_exception
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/_socket.py", line 382, in handle_exception
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/_socket.py", line 382, in handle_exception
  File "/Users/<user>/.m2/repository/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar/Lib/_socket.py", line 1193, in send
AttributeError: 'org.python.netty.channel.socket.nio.NioSocketChann' object has no attribute 'bytesBeforeUnwritable'

**Comment by pquentin** [comment]
This appears to be a Jython issue, maybe http://bugs.jython.org/issue2618? I don't think urllib3 can do anything about it. :(

Maybe Jython support could be tested as part of #1498?
