### ISSUE TITLE
App Engine Error with HTTPS

### ISSUE THREAD

**Issue by speedplane** [urllib3/urllib3#1503]
I believe the change in PR #1430 broke urllib3 on Google App Engine, which doesn't have `_tunnel_host` in its implementation of httplib. Not sure why this wasn't picked up by tests, but the fix is easy, simply adding `if getattr(self, '_tunnel_host', None)` part should go back in.

Below is a stacktrace of the error. Note that this is pure urllib3, no requests are being used.

```
Traceback (most recent call last):
  ...
  File "/project/updater/search_backend.py", line 1353, in setup
    "/_alias/%s"%self.index_name)
  File "/project/libs/elasticsearch_five/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/project/libs/elasticsearch_five/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/project/libs/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/project/libs/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/project/libs/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/project/libs/urllib3/connection.py", line 304, in connect
    if self._tunnel_host:
AttributeError: 'VerifiedHTTPSConnection' object has no attribute '_tunnel_host'
```

**Comment by speedplane** [comment]
See PR #1504 for the related PR.
