### ISSUE TITLE
Request raising exception only for HTTPS requests

### ISSUE THREAD

**Issue by gleopoldo** [urllib3/urllib3#1515]
Hello!

I have an python 2.7.3 application running with urllib3 1.24.1 and I'm getting an error when attempting to send a request through a proxy. Here is my example:
```
import urllib3
import os

proxy = urllib3.ProxyManager(os.environ['http_proxy'])
proxy.request("GET", "https://google.com")
```

I got this issue when running the request above on a misconfigured proxy: assuming that I'm making a request to google.com using HTTPS, I get a `ProxyError`:

```
$ pipenv run python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    proxy.request("GET", "https://google.com")
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 446, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/smtp-milter/.venv/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
```

However, by issuing a request to **http**://google.com, I get the same HTTP response status, but **without** the `ProxyError`.

In this second case, since the HTTP request didn't failed at first time, it's never retried and so it never raises the `MaxRetryError` that is raised in the first one. The HTTPS version is raising this ProxyError when the proxy returned the TUNNEL_REJECT, which leads after some retries to this "outer" error.

This inconsistency in the lib's API may lead to confusion when debugging... Can we have a single behavior for both scenarios? I mean either raising an error, or returning the request data, for both cases? WDYT?

**Comment by sethmlarson** [comment]
Thanks for opening this issue. I agree this is a little confusing from an API perspective but I think we're doing the right thing here.

When using HTTPS over a proxy there's an additional request that is done to create an HTTPS tunnel through the proxy and we're receiving a non-2XX response from the proxy when setting up that tunnel we raise a `ProxyError` because a tunnel couldn't be established.

HTTP requests lack this extra setup step so there are no errors when we receive a valid HTTP response back.

I'm going to close this issue for now, if you would like to reopen feel free to comment and we can discuss further.

**Comment by gleopoldo** [comment]
Nice! Thanks for the reply, @sethmlarson!
