### ISSUE TITLE
No module named 'urllib3.packages.six'

### ISSUE THREAD

**Issue by Qoyyuum** [urllib3/urllib3#1518]
``` python
>>> import urllib3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
>>> 
```

I checked that I have already installed `urllib3` and `six`.

``` sh
$ python -m pip install --upgrade --user urllib3
Requirement already up-to-date: urllib3 in /usr/lib/python3.6/site-packages (1.24.1)
```
``` sh
$ python -m pip install --upgrade --user six    
Requirement already up-to-date: six in ./.local/lib/python3.6/site-packages (1.12.0)
```

What am I missing?

**Comment by sethmlarson** [comment]
Do you by chance have a module or file locally called `urllib3`? I'm unable to reproduce this on a clean install in a virtualenv.

**Comment by Qoyyuum** [comment]
I installed it without a `virtualenv`. I've tested with a `pipenv` which is a better version of `virtualenv`, IMO and it does work. 

```
PS D:\MS1\Documents\piptest> pipenv shell
Creating a virtualenv for this project…
Using c:\python36\python.exe (3.6.5) to create virtualenv…
Already using interpreter c:\python36\python.exe
Using base prefix 'c:\\python36'
New python executable in C:\Users\MS1\.virtualenvs\piptest-2030i7_0\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\MS1\.virtualenvs\piptest-2030i7_0
Creating a Pipfile for this project…
Launching subshell in virtual environment. Type 'exit' to return.
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS D:\MS1\Documents\piptest> pip freeze
PS D:\MS1\Documents\piptest> pip install urllib3
Collecting urllib3
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 679kB/s
Installing collected packages: urllib3
Successfully installed urllib3-1.24.1
PS D:\MS1\Documents\piptest> python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>>
```
I thought that this might solve for [Variety's issue](https://github.com/varietywalls/variety/issues/124)

**Why is this any different between both Virtualenv and installed globally in pip install?**

**Comment by sigmavirus24** [comment]
A few things:

`Requirement already up-to-date: urllib3 in /usr/lib/python3.6/site-packages (1.24.1)` shows that you're using Linux and on many Linux distros, `pip` is broken (by the distro packagers) even when using `--user` to prefer the globally installed version installed by the distro package manager.

In many such cases, they also break packages because the package manager provided packages aren't intended for developers to use but for packages installed on the system to use (snapcraft, etc.).

> I installed it without a virtualenv. I've tested with a pipenv which is a better version of virtualenv,

I hate to burst your bubble, but Pipenv just uses virtualenv underneath everything. So it's exactly equal to using virtualenv just slower and with more indirection.

Next, you're new test is not on Linux but on Windows. Regardless, using a virtualenv on Linux would result in the same effect.

If you can give us something semi-consistent to work with, we might be able to assist, but I think the fundamental issue is relying on a distribution of urllib3 not provided by this team for development purposes and having a distro that applies arbitrary patches without sufficient testing.

**Comment by robert-shade** [comment]
For future generations, since this is the first hit in Google:  I just saw this same issue.  Root cause for me was that CentOS was trying to "unbundle" six and replaces the file with a symlink (https://git.centos.org/rpms/python-urllib3/blob/c8/f/SPECS/python-urllib3.spec#_85).  At some point six must have been uninstalled from the system by something other than dnf/yum, which broke the packaging.  Reinstalling the six package un-breaks things.

**Comment by pquentin** [comment]
Thank you @robert-shade for helping others out!

**Comment by ASBishop** [comment]
Yes, thank you @robert-shade! The fix worked for me.

**Comment by alex-hsp** [comment]
I had the same issue but the problem was that i was creating a pipenv virtualenv inside a folder that was forwarded to windows by vagrant. My guess is that was breaking some symlinks inside venv.

**Comment by rhmcruiser** [comment]
I encountered the same issue  "ModuleNotFoundError: No module named 'urllib3.packages.six' " 
even though the urllib and six modules are installed 

bash-5.0$ python3.7 release_readiness_criteria.py Bug-Report-QE-Dashboard
Traceback (most recent call last):
  File "release_readiness_criteria.py", line 3, in <module>
    from helpers import *
  File "/home/rmonther/bz-report/bugzilla-reports-tool/helpers.py", line 5, in <module>
    from config import *
  File "/home/rmonther/bz-report/bugzilla-reports-tool/config.py", line 1, in <module>
    import bugzilla
  File "/usr/local/lib/python3.7/site-packages/bugzilla/__init__.py", line 10, in <module>
    from .base import Bugzilla
  File "/usr/local/lib/python3.7/site-packages/bugzilla/base.py", line 21, in <module>
    from ._backendrest import _BackendREST
  File "/usr/local/lib/python3.7/site-packages/bugzilla/_backendrest.py", line 9, in <module>
    from ._backendbase import _BackendBase
  File "/usr/local/lib/python3.7/site-packages/bugzilla/_backendbase.py", line 6, in <module>
    import requests
  File "/usr/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six'                                                   <<<   Error 
bash-5.0$ 

bash-5.0$ sudo pip3 install urllib3 six
[sudo] password for rmonther: 
Requirement already satisfied: urllib3 in /usr/lib/python3.7/site-packages (1.25.7)                             <<  
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (1.15.0)                           << 
bash-5.0$

**Comment by migueelmm** [comment]
rt

**Comment by fosterseth** [comment]
seems `urllib3` expects `six` to be installed to the same site-packages location on your system

type `pip list -v` to see where they are located

**Comment by sethmlarson** [comment]
@fosterseth This is not the case for urllib3 installed from PyPI. Linux distros sometimes unbundle and mangle the code that we ship, but that is out of our control.

**Comment by kzlucas** [comment]
```
pip uninstall urllib3
pip install urllib3
```
Fix the issue for me on centOS

**Comment by dmc5179** [comment]
For me the issue was that I install the pip modules as root without noticing it. I pip uninstalled six urllib3 and then reinstalled them as my normal user. Solved the issue right away

**Comment by jackzhao12345** [comment]
Lower version 1.24.1,Can solve this problem.
It is estimated that your version is 1.26

**Comment by sethmlarson** [comment]
That version is vulnerable to multiple CVEs. Instead use latest versions of urllib3 and other packages.
