### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57362): Max retries exceeded with url: /session/b8c7e1f4-327f-482e-b7a8-4e2f417d7d51/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041B10D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by PythoNiko** [urllib3/urllib3#1653]
```
`import unittest
from selenium import webdriver


class MyTest(unittest.TestCase):

    `@classmethod
    def setUpClass(cls):
        # create a new Firefox session and move to trade-in page on storefront
        cls.driver = webdriver.Firefox(executable_path='my/path/to/geckodriver.exe')
        cls.driver.get('https://www.mysite.com')
        cls.driver.set_window_position(0, 0)
        cls.driver.set_window_size(1024, 768)
        cls.driver.implicitly_wait(5)
        cls.driver.maximize_window()
        
        # Go to X section
        cls.my_button = cls.driver.find_element_by_xpath(
            '/html/body/div[1]/div[2]/div[2]/div[2]/div[2]/div[3]/div[2]/a[2]')
        cls.my_button.click()

    def test_a(self):
        print('\n' + '_____Section A_____')

        # get a
        element_a = self.driver.find_element_by_xpath(
            '//*[@id="contentInnerWrap"]/div[1]/div[2]/div/div[1]/ul/li[1]/span').text
        #  do more stuff....

    def test_b(self):
        print('\n' + '_____Section B_____')

        # get b
        element_a = self.driver.find_element_by_xpath(
            '//*[@id="contentInnerWrap"]/div[1]/div[2]/div/div[1]/ul/li[1]/span').text
        #  do more stuff....

    @classmethod
    def tearDown(cls):
        # close the browser window
        cls.driver.quit()


if __name__ == '__main__':
    unittest.main(verbosity=2)`

This is my main test file. Worked fine with test_a alone.
As soon as I added test_b, I get the following error:

> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57362): Max retries exceeded with url: /session/b8c7e1f4-327f-482e-b7a8-4e2f417d7d51/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041B10D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Stacktrace:

``Error
Traceback (most recent call last):
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **myproject
ootdir\lib_request_kw)
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\myproject
ootdir\\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\myproject
ootdir\\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\myproject
ootdir\\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\myproject
ootdir\\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\myproject
ootdir\\client.py", line 956, in send
    self.connect()
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connection.py", line 183, in connect
    conn = self._new_conn()
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x041B10D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\my-name\AppData\Local\Programs\Python\Python37-32\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\my-name\PycharmProjects\my-project\test_trade_ins.py", line 86, in test_zzz
    self.driver.implicitly_wait(30)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 912, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\request.py", line 72, in request
    **urlopen_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    **response_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    **response_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    **response_kw)
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\my-name\PycharmProjects\my-project\venv\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=57362): Max retries exceeded with url: /session/b8c7e1f4-327f-482e-b7a8-4e2f417d7d51/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041B10D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by PythoNiko** [comment]
Apologies for horrific formatting, working on edit now...

**Comment by sethmlarson** [comment]
Have you tried starting your webdriver server and waiting a second before starting your client? That's what the top results on Google say about this issue.

**Comment by PythoNiko** [comment]
> Have you tried starting your webdriver server and waiting a second before starting your client? That's what the top results on Google say about this issue.

I have tried do plug in self.driver.implicitly_wait(30) between each test case if that's what you mean. Very new to this so apologies if I am asking very novice questions.

Currently running the entire script through Pycharm before attempting to have it automated and run through command line.

Does the webdriver server not restart automatically within the tearDown() method anyway?

**Comment by sethmlarson** [comment]
Try changing your implicity_wait(30) into a time.sleep(10).

**Comment by PythoNiko** [comment]
Same issue remains @sethmlarson , tried plugging it in a few places as well to be extra sure.

I've also just noticed Pycharm is highlighting 'driver' in cls.driver.quit() within the tearDown() method

Getting the following warning

'Unresolved attribute reference 'driver' for class...'

Possibly related? The tearDown() method might not be working at all then?

**Comment by LiLejia** [comment]
@PythoNiko  Hi,Niko, how does your bug go now? 
I encountered same problem working with Webdriver, but in my case, I cached a Webdriver instance as a global var  to share with different flask requests, if I just use `flask run app` every thing is OK, when it comes to GUnicorn with different fork process handling requests, the exceptions.MaxRetryError comes out.
I guess `PoolManager` might have something to do with pid?

**Comment by pquentin** [comment]
@LiLejia Do you also see `Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it now` in your `MaxRetryError`? `MaxRetryError` by itself is not very informative because many errors are handled this way.

**Comment by LiLejia** [comment]
@pquentin  I just found out that it's my own logic problem. I just changed urllib3 to http.client and it failed either. Thanks a lot. However, does this kind of threads shows that the `MaxRetryError` should update somehow? Just tell user you have a bad connectivity? 
> HTTPConnectionPool(host='127.0.0.1', port=57362): Max retries exceeded with url: /session/b8c7e1f4-327f-482e-b7a8-4e2f417d7d51/timeouts
This kind of log totally make me think it's a keep-alive/socket problem as I am new to this framework. 
Maybe it's just my problem.

@PythoNiko  If your problem still exists, make sure your `WebDriver` at `http://127.0.0.1:4444/wd/hub` is still alive.

**Comment by pquentin** [comment]
> However, does this kind of threads shows that the MaxRetryError should update somehow? Just tell user you have a bad connectivity?

Usually you see a "Caused by ..." message in the exception that points to the root cause. You can have a `MaxRetryError` exception in many situations, it's not always about bad connectivity!

**Comment by LiLejia** [comment]
@pquentin Got it! My mistake.

**Comment by efraim-lima** [comment]
I'm with same trouble, but I tried in another application with another code and it run, when I came to the main application it runs the error again.

I had tried some soluctions from from here: use sleep code after request webdriver, change the URL parameter, change for slice and nothing else works.

I managed to solve this error in my code just finding a line that was out of a indented block, I tink is not your case, sorry...
I find another discussion in another forum...try to see this link (Errno 10061 : No connection could be made because the target machine actively refused it ( client - server )), it's a similar case.

PS.: I'm new here, so I don't know if I can to make mention of another forum...sorry about that...

Good luck and Thanks for the help.

**Comment by inam4** [comment]
I got this error while using selenium. My "driver.get" was inside the loop while the driver path was outside. 
The error was resolved when I place the path inside the loop.
**Error code:**
```
website = ['www.google.com',....]
driver = webdriver.Chrome(executable_path=r"D:\...")
for i in website:
  driver.get(i)
  driver.quit()
```

**Correct code:**
```
website = ['www.google.com',....]
for i in website:
  driver = webdriver.Chrome(executable_path=r"D:\...")
  driver.get(i)
  driver.quit()

```

**Comment by Omar-elkhirani** [comment]
> I got this error while using selenium. My "driver.get" was inside the loop while the driver path was outside. The error was resolved when I place the path inside the loop. **Error code:**
> 
> ```
> website = ['www.google.com',....]
> driver = webdriver.Chrome(executable_path=r"D:\...")
> for i in website:
>   driver.get(i)
>   driver.quit()
> ```
> 
> **Correct code:**
> 
> ```
> website = ['www.google.com',....]
> for i in website:
>   driver = webdriver.Chrome(executable_path=r"D:\...")
>   driver.get(i)
>   driver.quit()
> ```

You are my man, this fixed the same issue i had for 3 days without solving it, now it's ok , thanks a loooot
