### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups' on simple PoolManager.request

### ISSUE THREAD

**Issue by MansM** [urllib3/urllib3#1731]
```
http = urllib3.PoolManager(maxsize=10)

url = "http://someaddress:32400/library/sections?"
token = "NotSharingIsSometimesCaring"
get = http.request(method='GET', url=url, headers={'X-Plex-Token': token})
```

Tried macos Mojave with Py 3.7.4 and in docker with python 3.8 
using urllib3  1.25.6

```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    get = http.request(method='GET', url=url, headers={'X-Plex-Token': token})
  File "/Users/someusername/Library/Python/3.7/lib/python/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/someusername/Library/Python/3.7/lib/python/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/someusername/Library/Python/3.7/lib/python/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/someusername/Library/Python/3.7/lib/python/site-packages/urllib3/connectionpool.py", line 615, in urlopen
    url = six.ensure_str(_encode_target(url))
  File "/Users/someusername/Library/Python/3.7/lib/python/site-packages/urllib3/util/url.py", line 328, in _encode_target
    path, query, fragment = TARGET_RE.match(target).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by pquentin** [comment]
Thank you for your bug report!

We need to fix our TARGET_RE regex, but in the meantime can you try removing the trailing slash in your `url`?

**Comment by MansM** [comment]
I will try without the trailing question mark. Wasn’t a trailing slash

**Comment by sethmlarson** [comment]
I've got a fix for this issue locally. Will create a PR.
