### ISSUE TITLE
Fails to load URL which ends with "?"

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#1738]
Urllib3 version is 1.25.6

Code
```python
from urllib3 import PoolManager

def main():
    mgr = PoolManager()
    res = mgr.request('GET', 'http://yandex.ru/?')
    print(res.status)

if __name__ == '__main__':
    main()
```

Fails with traceback:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    main()
  File "test.py", line 6, in main
    res = mgr.request('GET', 'http://yandex.ru/?')
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.5/dist-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 615, in urlopen
    url = six.ensure_str(_encode_target(url))
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/url.py", line 328, in _encode_target
    path, query, fragment = TARGET_RE.match(target).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by sethmlarson** [comment]
Yep, we've already fixed this issue. We just need to make a release which will happen soon.
