### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by lorien** [urllib3/urllib3#1764]
urllib 1.25.6
```
Traceback (most recent call last):
  File "/home/web/web/yandex/.env/lib/python3.5/site-packages/ioweb/network_service.py", line 177, in thread_network
    req, res, error, raise_network_error=False
  File "/home/web/web/yandex/.env/lib/python3.5/site-packages/ioweb/transport.py", line 310, in prepare_response
    self.read_with_timeout(req, res)
  File "/home/web/web/yandex/.env/lib/python3.5/site-packages/ioweb/transport.py", line 266, in read_with_timeout
    chunk = self.urllib3_response.read(chunk_size)
  File "/home/web/web/yandex/.env/lib/python3.5/site-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 501, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/home/web/web/yandex/.env/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 332, in recv_into
    raise ssl.SSLError("read error: %r" % e)
ssl.SSLError: ("read error: Error([('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')],)",)
```
Is it OK?
Should not it be `exceptions.SSLError` or something like that derived from urllib3 package?

**Comment by hodbn** [comment]
Hi @lorien!
Can you please submit a simple reproducing script?

**Comment by christopher-hesse** [comment]
I've seen this error as well.  Building a server that produces this message reliably sounds like a pain, but it should be clear from the stack trace that `urllib3` is allowing an SSLError to escape even though [lower level exceptions should be wrapped](https://urllib3.readthedocs.io/en/latest/user-guide.html#errors-exceptions).

Looking at the code here: https://github.com/urllib3/urllib3/blob/9971e27e83a891ba7b832fa9e5d2f04bbcb1e65f/src/urllib3/response.py#L437 it seems like if there is any SSLError besides a read timeout, it will end up hitting user code.

**Comment by sethmlarson** [comment]
@christopher-hesse I believe you're correct, we should be wrapping the `BaseSSLError` into a `urllib3.exceptions.SSLError` in line with the `_error_catcher()` contract of wrapping low-level Python exceptions into urllib3 exceptions.

**Comment by christopher-hesse** [comment]
Great!  I could see an argument for raising SSL errors such as invalid certs directly to the user.   The safest bet for this code could be just adding a special case for this `decryption failed or bad record mac` error similar to the existing read timeout handling.

Looking at https://github.com/christopher-hesse/blobfile/issues/43 it seems that there are different exceptions for different ssl libraries but they both contain that message, so that might look like:

```py
                if "read operation timed out" in str(e):
                    raise ReadTimeoutError(self._pool, None, "Read timed out.")
                elif "decryption failed or bad record mac" in str(e):
                    raise ProtocolError("SSL decryption error: %r" % e, e)
                else:
                    raise
```

**Comment by christopher-hesse** [comment]
It looks like `urllib3.exceptions.SSLError` says `Raised when SSL certificate fails in an HTTPS connection.` so it might be worth changing that documentation, or else special-casing this particular error with `if "decryption failed or bad record mac" in str(e): raise ProtocolError(...)`
