### ISSUE TITLE
Investigate PyPy test_release_conn_param_is_respected_after_timeout_retry failure

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1838]
Many PyPy failures just hang the test suite, which is really hard to debug. But today I've seen a real failure.

```
__ TestSocketClosing.test_release_conn_param_is_respected_after_timeout_retry __
Traceback (most recent call last):
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 431, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/pypy3.5-6.0.0/lib-python/3/http/client.py", line 1198, in getresponse
    response.begin()
  File "/opt/python/pypy3.5-6.0.0/lib-python/3/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/pypy3.5-6.0.0/lib-python/3/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python/pypy3.5-6.0.0/lib-python/3/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
_socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 682, in urlopen
    chunked=chunked,
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 433, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 341, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=37625): Read timed out. (read timeout=0.001)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/urllib3/urllib3/test/with_dummyserver/test_socketlevel.py", line 889, in test_release_conn_param_is_respected_after_timeout_retry
    timeout=Timeout(connect=LONG_TIMEOUT, read=SHORT_TIMEOUT),
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 770, in urlopen
    **response_kw
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/connectionpool.py", line 730, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/travis/build/urllib3/urllib3/.nox/test-pypy/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=37625): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=37625): Read timed out. (read timeout=0.001)",))
----------------------------- Captured stdout call -----------------------------
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /
------------------------------ Captured log call -------------------------------
WARNING  urllib3.connectionpool:connectionpool.py:755 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))': /
```

I'll need to investigate: is `read=SHORT_TIMEOUT` is appropriate here, of is something else wrong?

**Comment by pquentin** [comment]
Fixed in https://github.com/urllib3/urllib3/pull/1956/files
