### ISSUE TITLE
Jython 2.7.2 SSLError, internal error

### ISSUE THREAD

**Issue by lukicsl** [urllib3/urllib3#1849]
Jython has a problem with ssl:
This might be an issue at Jython, please give your guess

```
root@34b4e3a1e41b:/# python
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK Server VM (AdoptOpenJDK)] on java14
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://api.eiswarnung.de/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 369, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/jython/Lib/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/ (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))
>>> 
```

**Comment by sigmavirus24** [comment]
As I said on the requests issue this seems to be an issue with your request domain and jython

**Comment by sethmlarson** [comment]
Thanks @sigmavirus24 closing now.
