### ISSUE TITLE
Max retries exceeded with url: / (Caused by SSLError

### ISSUE THREAD

**Issue by WayneZeng** [urllib3/urllib3#1865]
import urllib3
http = urllib3.PoolManager(num_pools=1, maxsize=1, block=False)
r = http.request('GET', 'https://google.com')

evironment:
mac os
python 3.6.5
certifi==2018.4.16(the lastest version 2020.4.5.1 is also failed)
urllib3==1.25.7

the traceback is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

**Comment by sethmlarson** [comment]
Sounds like something is presenting a different certificate for "www.google.com" as it's not verifying properly with certifi (Mozilla's CA bundle)

**Comment by pquentin** [comment]
First, I doubt this is the exact snippet you used as you're not specifying https anywhere. So let's say you're trying to run `r = http.request("GET", "https://google.com/")`.

Starting from Python 3.6, the macOS installer from python.org does not include certificates by default, you need to click on "Install Certificates": https://www.python.org/downloads/release/python-365/

If you don't do that, you can use certifi, but while requests enables it for you, you need to do it yourself in urllib3. This should work:

```
import certifi
import urllib3

http = urllib3.PoolManager(ca_certs=certifi.where())
r = http.request("GET", "google.com")
```
