### ISSUE TITLE
test_delayed_body_read_timeout_with_preload is flaky

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1883]
Example failures:

 * https://github.com/urllib3/urllib3/runs/724263459?check_suite_focus=true (seen in https://github.com/urllib3/urllib3/pull/1867)

Log:

```
2020-05-31T04:32:39.1658820Z ________ TestSocketClosing.test_delayed_body_read_timeout_with_preload _________
2020-05-31T04:32:39.1659980Z Traceback (most recent call last):
2020-05-31T04:32:39.1663620Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
2020-05-31T04:32:39.1664020Z     (self._dns_host, self.port), self.timeout, **extra_kw
2020-05-31T04:32:39.1665550Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
2020-05-31T04:32:39.1665760Z     raise err
2020-05-31T04:32:39.1666450Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
2020-05-31T04:32:39.1666640Z     sock.connect(sa)
2020-05-31T04:32:39.1666770Z ConnectionRefusedError: [Errno 61] Connection refused
2020-05-31T04:32:39.1666830Z 
2020-05-31T04:32:39.1666950Z During handling of the above exception, another exception occurred:
2020-05-31T04:32:39.1667010Z 
2020-05-31T04:32:39.1667140Z Traceback (most recent call last):
2020-05-31T04:32:39.1667370Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/test/with_dummyserver/test_socketlevel.py", line 570, in test_delayed_body_read_timeout_with_preload
2020-05-31T04:32:39.1667540Z     pool.urlopen("GET", "/", retries=False, timeout=timeout)
2020-05-31T04:32:39.1668150Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
2020-05-31T04:32:39.1668340Z     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2020-05-31T04:32:39.1668950Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
2020-05-31T04:32:39.1669170Z     raise six.reraise(type(error), error, _stacktrace)
2020-05-31T04:32:39.1669840Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
2020-05-31T04:32:39.1669990Z     raise value
2020-05-31T04:32:39.1670620Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
2020-05-31T04:32:39.1670770Z     chunked=chunked,
2020-05-31T04:32:39.1671360Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
2020-05-31T04:32:39.1671540Z     conn.request(method, url, **httplib_request_kw)
2020-05-31T04:32:39.1671720Z   File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/http/client.py", line 1252, in request
2020-05-31T04:32:39.1671870Z     self._send_request(method, url, body, headers, encode_chunked)
2020-05-31T04:32:39.1672060Z   File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/http/client.py", line 1298, in _send_request
2020-05-31T04:32:39.1672200Z     self.endheaders(body, encode_chunked=encode_chunked)
2020-05-31T04:32:39.1672390Z   File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/http/client.py", line 1247, in endheaders
2020-05-31T04:32:39.1672510Z     self._send_output(message_body, encode_chunked=encode_chunked)
2020-05-31T04:32:39.1673070Z   File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/http/client.py", line 1026, in _send_output
2020-05-31T04:32:39.1673360Z     self.send(msg)
2020-05-31T04:32:39.1673610Z   File "/Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/python3.7/http/client.py", line 966, in send
2020-05-31T04:32:39.1673770Z     self.connect()
2020-05-31T04:32:39.1674440Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connection.py", line 189, in connect
2020-05-31T04:32:39.1674550Z     conn = self._new_conn()
2020-05-31T04:32:39.1675160Z   File "/Users/runner/runners/2.263.0/work/urllib3/urllib3/.nox/test-3-7/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
2020-05-31T04:32:39.1675330Z     self, "Failed to establish a new connection: %s" % e
2020-05-31T04:32:39.1676490Z urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10c8c03d0>: Failed to establish a new connection: [Errno 61] Connection refused
```

**Comment by sethmlarson** [comment]
I haven't seen this test being as flaky lately (at least any more than any other timeout test?) so I'm going to close this. Let me know if this is still a problem that I'm missing.

**Comment by pquentin** [comment]
I think it's still flaky but this issue isn't helping.
