### ISSUE TITLE
ProxyManager with HTTP proxy, too many redirects

### ISSUE THREAD

**Issue by lemon-bean** [urllib3/urllib3#1899]
After following the instruction in [urllib3 document](https://urllib3.readthedocs.io/en/latest/advanced-usage.html), I tried this code

```
import urllib3

proxy = urllib3.ProxyManager('http://localhost:1187')
proxy.request('GET', 'http://google.com/')
```

And I got this result:

```
Traceback (most recent call last):
  File "/Users/Kable/Documents/2_AI/TF_projects/proxy_testing.py", line 70, in <module>
    test_urllib()
  File "/Users/Kable/Documents/2_AI/TF_projects/proxy_testing.py", line 13, in test_urllib
    r1 = proxy.request('GET', 'http://google.com/')
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 488, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 378, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 488, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 378, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 488, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 378, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 488, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/poolmanager.py", line 365, in urlopen
    retries = retries.increment(method, url, response=response, _pool=conn)
  File "/Users/Kable/Documents/2_AI/TF_projects/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
**urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1187)**: Max retries exceeded with url: http://www.google.com/ (Caused by ResponseError('too many redirects'))
```

What can I do to get it to work?

**Comment by sethmlarson** [comment]
Try turning on debug logging to see what your redirects are. Since this likely isn't a defect with the library I'm going to close this issue.

**Comment by lemon-bean** [comment]
Thanks for your suggestion!
