### ISSUE TITLE
SSLError: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bendavis78** [urllib3/urllib3#1925]
I'm getting an intermittent error on my production Django website (running under UWSGI) when trying to use the kubernetes client library. The error seems to be with urllib3:

    Traceback (most recent call last):                                                
      File "/srv/hive/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 353, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)           
    FileNotFoundError: [Errno 2] No such file or directory 

The strange thing is, I can simply restart my server and the problem goes away, but after a few hours I see the same error again.

I added some extra logging to the `load_verify_locations` function in `urllib3/util/ssl_.py` to see what file it's trying to open. The `ca_certs` argument is passing in a temp file, `/tmp/tmp2xng8a6e`. The other two arguments are `None`. 

So, why a temp file, and why is it missing? Is there a reason why the temp file would get deleted, or why urllib3 might not be creating the temp file in the first place?

Here's the full exception with traceback:

    Aug 20 10:36:05 ERROR django.request: Internal Server Error: /code/projects/test-project/
    Traceback (most recent call last):
      File "/srv/hive/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 353, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
    FileNotFoundError: [Errno 2] No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
        chunked=chunked,
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
        self._validate_conn(conn)
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
        conn.connect()
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
        ssl_context=context,
      File "/srv/hive/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
        raise SSLError(e)
    urllib3.exceptions.SSLError: [Errno 2] No such file or directory
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/hive/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
        response = get_response(request)
      File "/srv/hive/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/srv/hive/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/srv/hive/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/srv/hive/src/hive/ide/views.py", line 67, in ide
        utils.init_workspace(project)
      File "/srv/hive/src/hive/ide/utils.py", line 252, in init_workspace
        get_user_storage_resource(project.user).apply()
      File "/srv/hive/src/hive/ide/utils.py", line 79, in apply
        responses.append(item.apply())
      File "/srv/hive/src/hive/ide/utils.py", line 221, in apply
        if self.exists:
      File "/srv/hive/src/hive/ide/utils.py", line 165, in exists
        self._call('read')
      File "/srv/hive/src/hive/ide/utils.py", line 152, in _call
        return func(**kwargs)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 18854, in read_namespaced_persistent_volume_claim
        (data) = self.read_namespaced_persistent_volume_claim_with_http_info(name, namespace, **kwargs)  # noqa: E501
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 18945, in read_namespaced_persistent_volume_claim_with_http_info
        collection_formats=collection_formats)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api
        _preload_content, _request_timeout)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
        _request_timeout=_request_timeout)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 366, in request
        headers=headers)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/rest.py", line 241, in GET
        query_params=query_params)
      File "/srv/hive/lib/python3.6/site-packages/kubernetes/client/rest.py", line 214, in request
        headers=headers)
      File "/srv/hive/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
        method, url, fields=fields, headers=headers, **urlopen_kw
      File "/srv/hive/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
        return self.urlopen(method, url, **extra_kw)
      File "/srv/hive/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
        **response_kw
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
        **response_kw
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
        **response_kw
      File "/srv/hive/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/srv/hive/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ide-ideresourcegroup-207977-dbdb0faf.hcp.centralus.azmk8s.io', port=443): Max retries exceeded with url: /api/v1/namespaces/ide/persistentvolumeclaims/workspace-storage-5p2lm91r (Caused by SSLError(FileNotFoundError(2, 'No such file or directory'),))

**Comment by sethmlarson** [comment]
The temporary file is not happening on our side, that is coming from somewhere else in your stack. I'd look for `tempfile` and mentions of `ssl_ca_cert` into your Kubernetes client config. Could be something about your dev setup that generates a temporary server certificate and saves it to a temporary location?
