### ISSUE TITLE
LocationParseError on every URL with default installation via apt-get on Parrot OS

### ISSUE THREAD

**Issue by delta-plus** [urllib3/urllib3#1972]
Lots of Parrot OS security tools depend on the python3-urllib3 package, so I have it installed. pip3 freeze reports it as version 1.25.9. This all seemed to have gone pretty well but when I tried to use urllib3 from a python3 prompt, I keep getting LocationParseError on everything I try to connect to. Additionally, trying to connect to Apache2 via http://127.0.0.1 gives me another weird error involving the six module. Six is the latest version, 1.15, installed via the python3-six package. This is a fresh install of the latest Parrot OS, so if I messed anything up in this short amount of time it would be a new record for me. Any help would be greatly appreciated.

Example:
```python
Python 3.8.5 (default, Aug  2 2020, 15:09:07) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'https://www.wikipedia.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 324, in urlopen
    u = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://www.wikipedia.org
>>> r = http.request('GET', 'http://127.0.0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 324, in urlopen
    u = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 407, in parse_url
    ensure_func = six.ensure_text
AttributeError: module 'six' has no attribute 'ensure_text'
```

**Comment by sethmlarson** [comment]
v1.12 of six added support for ensure_text. Maybe Parrot OS unbundling isn't working properly?

Might need you to dig into your system Python's packages to solve this one. You can check `print(sys.path)`

**Comment by delta-plus** [comment]
Yeah, I'm pretty sure I just messed something up when I forgot to install a certain tool in a virtualenv. Did an even fresher install and urllib3 works fine. I have backups so the only thing I'm losing is half a day. Thanks for the help!
