### ISSUE TITLE
socket.timeout re-raised as ProtocolError

### ISSUE THREAD

**Issue by Dobatymo** [urllib3/urllib3#1981]
When using the requests library, I encountered a `socket.timeout` exception wrapped in a `ProtocolError`, wrapped in a requests.ConnectionError. Imo it should be converted to a `TimeoutError` instead.

Stupid me messed up copy and pasting the traceback, however I think I found where this issue originates from. `SocketError`s are caught [here](https://github.com/urllib3/urllib3/blob/6c429006c73da330b3c7e5b349a9a4b0eaf5d609/src/urllib3/connectionpool.py#L729) and converted [here](https://github.com/urllib3/urllib3/blob/6c429006c73da330b3c7e5b349a9a4b0eaf5d609/src/urllib3/connectionpool.py#L742)

Now because `isinstance(timeout(), error) == True` socket timeouts are caught and reraised as `ProtocolError` as well.

**Comment by sethmlarson** [comment]
I wish you had the traceback because as far as I can see for `HTTPConnectionPool._make_request()` everywhere where I/O happens is wrapped in `try...except (SocketTimeout): self._raise_timeout(...)` which in theory should wrap all `SocketTimeout` into `ReadTimeoutError`. If you find the traceback from this issue again it'd be really great to have.

**Comment by Dobatymo** [comment]
I just encountered the error again today. I was using the https://github.com/jjjake/internetarchive application, which uses `requests`, which uses `urllib3`. So you can ignore the bottom third of the traceback, I just included it for completeness.

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python37\lib\http\client.py", line 987, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Python37\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python37\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Program Files\Python37\lib\http\client.py", line 987, in send
    self.sock.sendall(data)
  File "C:\Program Files\Python37\lib\ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "C:\Program Files\Python37\lib\ssl.py", line 1003, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repositories\forks\internetarchive\internetarchive\item.py", line 975, in upload_file
    **request_kwargs)
  File "D:\repositories\forks\internetarchive\internetarchive\session.py", line 521, in send
    raise e
  File "D:\repositories\forks\internetarchive\internetarchive\session.py", line 518, in send
    reraise_modify(e, e.request.url, prepend=False)
  File "D:\repositories\forks\internetarchive\internetarchive\utils.py", line 338, in reraise_modify
    traceback)
  File "C:\Program Files\Python37\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "D:\repositories\forks\internetarchive\internetarchive\session.py", line 515, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', timeout('The write operation timed out')), 'https://the-url........')

```

**Comment by Dobatymo** [comment]
It seems https://github.com/urllib3/urllib3/blob/d3fc8468b3b27e6fab4cc366b1b6d299ee8321f2/src/urllib3/connectionpool.py#L394 is the culprit, no?

SocketTimeout is not handled there.

**Comment by sethmlarson** [comment]
Ah it'd a write timeout you're experiencing, huh. I figured that `request()` and `request_chunked()` would be robust against that.

What OS, Python and urllib3 version are you using by the way?

**Comment by Dobatymo** [comment]
I am using
OS: Win 7 x64 (latest updates)
Python: Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
urllib3: 1.25.8

I will update to the latest version 1.25.10 and see if that improves anything. But I don't think this was fixed inbetween versions, skimming the code.

**Comment by Ayke** [comment]
I'm seeing a similar one, here's my traceback:

`Traceback (most recent call last):
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='static3.porn-images-xxx.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lyaul\Desktop\photoDownloader.py", line 276, in <module>
    if getPicture(imgURL) != 200:
  File "C:\Users\lyaul\Desktop\photoDownloader.py", line 218, in getPicture
    response = requests.get(url, timeout=5, headers=headers)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 697, in send
    r.content
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Users\lyaul\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='static3.porn-images-xxx.com', port=443): Read timed out.`

And my system configuration:
Windows 10 x64, 
python 3.9.1,
urllib3 1.26.6
requests 2.25.1

The code was something like `response = requests.get(url, timeout=5, headers=headers)`, but since the earliest exception is socket, then urllib3, I think it's an issue of urllib3 instead of requests

**Comment by sigmavirus24** [comment]
@Ayke even the least charitable of reads of Seth's statement makes it clear this is a bug in urllib3. It hasn't been fixed yet. You don't need to argue the case that it's a urllib3 bug. We're aware of that

**Comment by Ayke** [comment]
> @Ayke even the least charitable of reads of Seth's statement makes it clear this is a bug in urllib3. It hasn't been fixed yet. You don't need to argue the case that it's a urllib3 bug. We're aware of that

Thanks for reminding me, I was just making clear that my case was identical to Dobatymo's case. You can of course safely ignore my arguments if you've already accepted my point.

**Comment by stvhay** [comment]
Any workaround for this issue?
