### ISSUE TITLE
HTTPSConnectionPool(host='www.amd.com', port=443): Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by jpdsceu** [urllib3/urllib3#1996]
Hello.

I am using urllib3 which connects to https://www.amd.com/en/support/chipsets/amd-socket-am4/x570
However, I am getting below error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.amd.com', port=443): Read timed out. (read timeout=60)
```

Any other site works fine and through the container AMD.com is pingable.

Any clue what it could be?

Thank you

**Comment by sethmlarson** [comment]
AMD is likely doing filtering based on HTTP headers as I confirmed locally. When I send the exact headers that my browser sends you receive a successful response. I don't know exactly which headers are required, but these are the ones I sent that worked:

```
User-Agent: <redacted>
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: <redacted>
Upgrade-Insecure-Requests: 1
If-Modified-Since: <redacted>
If-None-Match: <redacted>
Cache-Control: max-age=0
```

Since this isn't a defect in urllib3 I'm going to recommend a close. Hopefully this is enough information for you to make progress?

**Comment by jpdsceu** [comment]
Thanks A million! I completly forgot to check the HTTP headers.
It was: `User-Agent: <redacted>`

Have a great weekend.
