### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused 

### ISSUE THREAD

**Issue by kev26** [urllib3/urllib3#2031]
### Subject

Hi, I'm a newbie and I coded a python script to track the price of Amazon products. My code works well for 15 minutes before I got this error and I think that because I try to get the URL many times in a soft period of time by using "While = True and time.sleep(60)" to check the price every minute! Any solution for this case? Thank you so much for any advice !!!

### Environment

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC
import smtplib, ssl
from smtplib import SMTPAuthenticationError
from email.message import EmailMessage
import time
import chromedriver_binary
    
def getinfo():
    options = Options()
    options.add_argument("--headless")
    options.add_argument('--no-sandbox')
    options.add_argument("--window-size=1280,720")
    options.add_argument("—disable-gpu")
    options.add_argument('--disable-dev-sh-usage')
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
 
    driver = webdriver.Chrome(options=options)
    
    while True:
        driver.get(URL)
        try:
            element = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, product_id)))
            break
        except TimeoutException:
            print('TimeoutException')
            driver.quit()
            
    
    product_title = driver.find_element_by_id(product_id).text
    try:
        product_price = driver.find_element_by_id(price_id).text[1:]
        
    except:
        product_price = None
        print('NONE')
 
    driver.quit()
    return{
        "title": product_title,
        "price": product_price
    }
 
def send_mail(product):
    #CODE
 
while(True):
 
    URL = "https://www.amazon.com/gp/product/B08BB9RWXD"
 
    MAX_PRICE = '1000'
 
    product_id = 'productTitle'
    price_id = 'priceblock_ourprice'
 
    product_info = getinfo()
 
    if float(product_info["price"]) <= float(MAX_PRICE):
        send_mail(product_info)
 
    time.sleep(60)
 
```

### This is errors:

```
TimeoutException
Traceback (most recent call last):
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f257152a3c8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amztrack.py", line 83, in <module>
    product_info = getinfo()
  File "amztrack.py", line 35, in getinfo
    driver.get(URL)
  File "/home/huy/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/huy/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/huy/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/huy/.local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 767, in urlopen
    **response_kw
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/huy/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=53007): Max retries exceeded with url: /session/0ac51aff2db636bd20a43402f836e8d1/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f257152a3c8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by pquentin** [comment]
This isn't an urllib3 issue, closing. Please pay more attention to the options we presented to you when opening an issue next time.
