### ISSUE TITLE
Issue with TimeoutError: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by summer59423** [urllib3/urllib3#2084]
hey guys,  i'm a beginner of python and i wrote some code which can convert between an address and a coordinate with googlemaps API. Here's my code:

```
import googlemaps

gmaps = googlemaps.Client(key='myapikey')
geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')
print(geocode_result)
```

It works perfect in last couple mouths until these days it shows:
```
Traceback (most recent call last):
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1106544e0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/summer/PycharmProjects/poicrawler/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/geocode/json?address=newyork&key=myapikey (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1106544e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

```
 I'v tried these things below:
1.  I checked my API, it works, GoogleAPI support team said so too.
2. I tried same code in another network environment, failed.
3.  I tried same code with another mac in same network environment, it works.
4.  I updated those moduels related, still failed.
5. According to documentation i tried the url below it works but when i tried to get it from Requests module,  "[Errno 60] Operation timed out" comes again.
```
https://maps.googleapis.com/maps/api/geocode/json?address=Winnetka&key=myapikey
```

I'm totally confused, Any help or advice will be appreciate!!

**Comment by sethmlarson** [comment]
This issue tracker is for reporting defects with urllib3, this appears to be a question about usage. You should try on StackOverflow instead.

**Comment by summer59423** [comment]
> This issue tracker is for reporting defects with urllib3, this appears to be a question about usage. You should try on StackOverflow instead.

Oh sorry i m new here, thanks a lot, i will move the question there.
