### ISSUE TITLE
Max retries exceeded with url due to CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by marcelloromani** [urllib3/urllib3#2189]
### Subject

I cannot access `api.cloudflare.com` with their Python module due to this error:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: /client/v4/zones (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))
```

### Environment

```bash
OS macOS-11.2.3-x86_64-i386-64bit
Python 3.9.2
urllib3 1.26.4
requests 2.25.1
```

### Steps to Reproduce

```python
import requests
requests.get("https://api.cloudflare.com")
```

### Expected Behavior

I should get an HTTP/200 response with an authentication error since I'm not providing any username/password or token.

### Actual Behavior

```
Python 3.9.2 (default, Feb 24 2021, 13:26:09)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get("https://api.cloudflare.com")
Traceback (most recent call last):
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/marcello.romani/Documents/github/trekkie-toolkit/cloudflare/venv/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))
```

### Related issues:

https://github.com/urllib3/urllib3/issues/1865

https://github.com/cloudflare/python-cloudflare/issues/115

https://github.com/Homebrew/homebrew-core/issues/42198

**Comment by marcelloromani** [comment]
*Update*

The problem was caused by a network monitoring app installed by the company which intercepts the traffic, but most probably has exceptions for various DNS domains, which makes its behaviour look inconsistent.

Disabling the app temporarily made the issue go away.
