### ISSUE TITLE
Understand OpenSSL 3.0 failures

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2477]
OpenSSL 3 is supported by Python, we should try running urllib3's test suite against Python using OpenSSL 3.

Easiest route might be to use Docker in GitHub Actions with Fedora's "rawhide" image:
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
- https://hub.docker.com/_/fedora

### Minimum requirements

:dollar: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

- [ ] Add to the `ci` GitHub Action in the `main` branch to test against a platform with access to OpenSSL 3.
- [x] Create a pytest marker `@requires_openssl_lt_3` which adds `pytest.mark.xfail` to tests when Python is compiled with OpenSSL >= 3.0.0
- [x] For each failing test on CI figure out why the failure is occurring, document each failure with a comment and add the above pytest marker to the test.
- [x] Create a GitHub issue which summarizes all the problems that are currently failing tests

**Comment by pquentin** [comment]
I haven't worked on the GitHub Actions part (this part is still up for grabs!), but came up with a Dockerfile:

```
FROM fedora:rawhide

RUN dnf install -y git-core pipx

ENV PATH=/root/.local/bin:$PATH
RUN pipx install nox

RUN git clone https://github.com/urllib3/urllib3.git
WORKDIR /urllib3

# If we don't create the venv for nox, it fails with:
# nox > Program python not found.
# And if I make a symlink from /usr/bin/python to /usr/bin/python3, I get:
# nox > Warning: python3 is not installed into the virtualenv, it is located at /usr/bin/python3. This might cause issues! Pass external=True into run() to silence this message.
# /usr/bin/python3: No module named pip
RUN /usr/bin/python3 -m venv .nox/test-3-10
RUN ls .nox/test-3-10/bin
RUN nox -rs test-3.10
```

Just run it using `docker build .`. To compare with OpenSSL 1.1.1, just use "fedora:35" instead. This is useful because there are errors with the Python shipped by Fedora that are not about the switch to OpenSSL 3.0.0. Here are the six errors that are specific to OpenSSL 3.0.0:

```
______________________ TestSocketSSL.test_ssl_read_timeout ______________________
Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 530, in wrap_socket
    cnx.do_handshake()
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/OpenSSL/SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/OpenSSL/SSL.py", line 1607, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 412, in _make_request
    self._validate_conn(conn)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 1027, in _validate_conn
    conn.connect()
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connection.py", line 505, in connect
    self.sock = ssl_wrap_socket(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 539, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 583, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 533, in wrap_socket
    raise timeout("select timed out") from e  # type: ignore[arg-type]
TimeoutError: select timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 708, in urlopen
    httplib_response = self._make_request(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 414, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='localhost', port=39359): Read timed out. (read timeout=0.01)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 1255, in test_ssl_read_timeout
    response = pool.urlopen(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 766, in urlopen
    retries = retries.increment(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/retry.py", line 509, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=39359): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=39359): Read timed out. (read timeout=0.01)"))
```

```
____________ TestSocketSSL.test_ssl_failed_fingerprint_verification ____________
Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 1305, in test_ssl_failed_fingerprint_verification
    assert isinstance(cm.value.reason, SSLError)
AssertionError: assert False
 +  where False = isinstance(ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=41755): Read timed out. (read timeout=0.01)"), SSLError)
 +    where ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=41755): Read timed out. (read timeout=0.01)") = MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41755): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41755): Read timed out. (read timeout=0.01)"))').reason
 +      where MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41755): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41755): Read timed out. (read timeout=0.01)"))') = <ExceptionInfo MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41755): Max retries exceeded with url: / (C...eadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41755): Read timed out. (read timeout=0.01)"))') tblen=4>.value
```

```
_________ TestSocketSSL.test_ssl_custom_validation_failure_terminates __________
Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 530, in wrap_socket
    cnx.do_handshake()
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/OpenSSL/SSL.py", line 1894, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/OpenSSL/SSL.py", line 1607, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 412, in _make_request
    self._validate_conn(conn)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 1027, in _validate_conn
    conn.connect()
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connection.py", line 505, in connect
    self.sock = ssl_wrap_socket(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 539, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 583, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 533, in wrap_socket
    raise timeout("select timed out") from e  # type: ignore[arg-type]
TimeoutError: select timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 1490, in test_ssl_custom_validation_failure_terminates
    pool.request("GET", "/", retries=False, timeout=LONG_TIMEOUT)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/_request_methods.py", line 108, in request
    return self.request_encode_url(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/_request_methods.py", line 141, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 766, in urlopen
    retries = retries.increment(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/retry.py", line 439, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/util.py", line 37, in reraise
    raise value
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 708, in urlopen
    httplib_response = self._make_request(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 414, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='localhost', port=33009): Read timed out. (read timeout=0.01)
```

```
______ TestSocketClosing.test_closing_response_actually_closes_connection ______
Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 864, in test_closing_response_actually_closes_connection
    assert successful, "Timed out waiting for connection close"
AssertionError: Timed out waiting for connection close
assert False
```

```
________________________ TestSSL.test_ssl_read_timeout _________________________
Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 412, in _make_request
    self._validate_conn(conn)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 1027, in _validate_conn
    conn.connect()
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connection.py", line 505, in connect
    self.sock = ssl_wrap_socket(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 539, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/ssl_.py", line 583, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib64/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 708, in urlopen
    httplib_response = self._make_request(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 414, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='localhost', port=43137): Read timed out. (read timeout=0.01)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 1255, in test_ssl_read_timeout
    response = pool.urlopen(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/connectionpool.py", line 766, in urlopen
    retries = retries.increment(
  File "/urllib3/.nox/test-3-10/lib64/python3.10/site-packages/urllib3/util/retry.py", line 509, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=43137): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=43137): Read timed out. (read timeout=0.01)"))
```

```
_______________ TestSSL.test_ssl_failed_fingerprint_verification _______________
Traceback (most recent call last):
  File "/urllib3/test/with_dummyserver/test_socketlevel.py", line 1305, in test_ssl_failed_fingerprint_verification
    assert isinstance(cm.value.reason, SSLError)
AssertionError: assert False
 +  where False = isinstance(ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=41397): Read timed out. (read timeout=0.01)"), SSLError)
 +    where ReadTimeoutError("HTTPSConnectionPool(host='localhost', port=41397): Read timed out. (read timeout=0.01)") = MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41397): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41397): Read timed out. (read timeout=0.01)"))').reason
 +      where MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41397): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41397): Read timed out. (read timeout=0.01)"))') = <ExceptionInfo MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=41397): Max retries exceeded with url: / (C...eadTimeoutError("HTTPSConnectionPool(host=\'localhost\', port=41397): Read timed out. (read timeout=0.01)"))') tblen=4>.value
```

**Comment by sethmlarson** [comment]
According to Christian, OpenSSL 3.0 support added in Python 3.10 is experimental: https://mail.python.org/archives/list/python-dev@python.org/thread/ATO4DM6QYZGLSGGDZ3TRN5X3QDD5OHOE/

**Comment by sethmlarson** [comment]
We've decided to deprioritize OpenSSL 3.0 support as it's still "experimental" in Python 3.11 and there isn't an indication it will be stable in 3.12.

**Comment by illia-v** [comment]
> Looks like Ubuntu 22.04 is shipping with Python 3.10 as `python3` that has OpenSSL 3.0.2:

#2626 makes tests run on Ubuntu 22.04, tests succeed on Python 3.9 and 3.10.

---

I ran tests on Fedora 36 locally too, and found timeouts similar to https://github.com/urllib3/urllib3/issues/2477#issuecomment-966975130 there, but increasing `LONG_TIMEOUT` to 0.05 fixed them.
https://github.com/urllib3/urllib3/blob/9fbab29644bfc8068eb2082d0f25726c91813337/test/__init__.py#L80

---

Also, three other failures happened in Fedora 36 because the test method assumes that `ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT).maximum_version` will always be equal to `ssl.TLSVersion.MAXIMUM_SUPPORTED`.

https://github.com/urllib3/urllib3/blob/622aa69a1f65459232cadf7ff09f9a847d4c89b4/test/with_dummyserver/test_https.py#L947-L950

The assumption is not always true, and it's actually false for Fedora 36. [This](https://github.com/python/cpython/blob/e91b0a7139d4a4cbd2351ccb5cd021a100cf42d2/Modules/_ssl.c#L3534-L3542) is a related code in CPython. And `SSL_CTX_ctrl` can return different values depending on how OpenSSL has been compiled probably. I do not think this is related to OpenSSL 3.0 specifically.

```
__________________________________________________________________________________________ TestHTTPS.test_default_ssl_context_ssl_min_max_versions ___________________________________________________________________________________________

self = <test.with_dummyserver.test_https.TestHTTPS object at 0x7f6d8b313880>

    def test_default_ssl_context_ssl_min_max_versions(self) -> None:
        ctx = urllib3.util.ssl_.create_urllib3_context()
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2
>       assert ctx.maximum_version == ssl.TLSVersion.MAXIMUM_SUPPORTED
E       AssertionError: assert <TLSVersion.TLSv1_3: 772> == <TLSVersion.MAXIMUM_SUPPORTED: -1>
E        +  where <TLSVersion.TLSv1_3: 772> = <ssl.SSLContext object at 0x7f6d8b00f6c0>.maximum_version
E        +  and   <TLSVersion.MAXIMUM_SUPPORTED: -1> = <enum 'TLSVersion'>.MAXIMUM_SUPPORTED
E        +    where <enum 'TLSVersion'> = ssl.TLSVersion

test/with_dummyserver/test_https.py:950: AssertionError
______________________________________________________________________________________ TestHTTPS_TLSv1_2.test_default_ssl_context_ssl_min_max_versions _______________________________________________________________________________________

self = <test.with_dummyserver.test_https.TestHTTPS_TLSv1_2 object at 0x7f6d8b29c070>

    def test_default_ssl_context_ssl_min_max_versions(self) -> None:
        ctx = urllib3.util.ssl_.create_urllib3_context()
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2
>       assert ctx.maximum_version == ssl.TLSVersion.MAXIMUM_SUPPORTED
E       AssertionError: assert <TLSVersion.TLSv1_3: 772> == <TLSVersion.MAXIMUM_SUPPORTED: -1>
E        +  where <TLSVersion.TLSv1_3: 772> = <ssl.SSLContext object at 0x7f6d897e6040>.maximum_version
E        +  and   <TLSVersion.MAXIMUM_SUPPORTED: -1> = <enum 'TLSVersion'>.MAXIMUM_SUPPORTED
E        +    where <enum 'TLSVersion'> = ssl.TLSVersion

test/with_dummyserver/test_https.py:950: AssertionError
______________________________________________________________________________________ TestHTTPS_TLSv1_3.test_default_ssl_context_ssl_min_max_versions _______________________________________________________________________________________

self = <test.with_dummyserver.test_https.TestHTTPS_TLSv1_3 object at 0x7f6d8b2a14e0>

    def test_default_ssl_context_ssl_min_max_versions(self) -> None:
        ctx = urllib3.util.ssl_.create_urllib3_context()
        assert ctx.minimum_version == ssl.TLSVersion.TLSv1_2
>       assert ctx.maximum_version == ssl.TLSVersion.MAXIMUM_SUPPORTED
E       AssertionError: assert <TLSVersion.TLSv1_3: 772> == <TLSVersion.MAXIMUM_SUPPORTED: -1>
E        +  where <TLSVersion.TLSv1_3: 772> = <ssl.SSLContext object at 0x7f6d897e6440>.maximum_version
E        +  and   <TLSVersion.MAXIMUM_SUPPORTED: -1> = <enum 'TLSVersion'>.MAXIMUM_SUPPORTED
E        +    where <enum 'TLSVersion'> = ssl.TLSVersion

test/with_dummyserver/test_https.py:950: AssertionError
```

**Comment by sethmlarson** [comment]
@illia-v Thank you for your analysis! This is all looking great.

Your observation about default minimum TLS version being a compile-able option is true, we should open a separate issue for this so when platforms inevitable bump to TLS 1.3+ we don't start seeing failures.

**Comment by tiran** [comment]
No, it's not a compile-time option. It's actually more complicated and depends on several things like downstream patches and system-wide settings.

- With upstream OpenSSL 3.0.x, the call ``SSL_CTX_ctrl(ctx, SSL_CTRL_GET_MAX_PROTO_VERSION, 0, NULL)`` returns ``0``, which Python maps to ``TLSVersion.MAXIMUM_SUPPORTED``
- Downstream OpenSSL in Fedora, Ubuntu, and other distros are patched and use custom crypto policies. With Fedora downstream OpenSSL 3.0, the ``SSL_CTX_ctrl(ctx, SSL_CTRL_GET_MAX_PROTO_VERSION, 0, NULL)`` returns the settings based on ``/etc/crypto-policies/back-ends/opensslcnf.config``.

The [``DEFAULT``](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/blob/master/policies/DEFAULT.pol) crypto policy sets TLS 1.2 as minimum and TLS 1.3 as maximum:

```
$ cat /etc/crypto-policies/back-ends/opensslcnf.config
CipherString = @SECLEVEL=1:kEECDH:kRSA:kEDH:kPSK:kDHEPSK:kECDHEPSK:kRSAPSK:-aDSS:-3DES:!DES:!RC4:!RC2:!IDEA:-SEED:!eNULL:!aNULL:!MD5:-SHA384:-CAMELLIA:-ARIA:-AESCCM8
Ciphersuites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256
TLS.MinProtocol = TLSv1.2
TLS.MaxProtocol = TLSv1.3
DTLS.MinProtocol = DTLSv1.2
DTLS.MaxProtocol = DTLSv1.2
SignatureAlgorithms = ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:ed25519:ed448:rsa_pss_pss_sha256:rsa_pss_pss_sha384:rsa_pss_pss_sha512:rsa_pss_rsae_sha256:rsa_pss_rsae_sha384:rsa_pss_rsae_sha512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224
```

You can override the settings by setting ``OPENSSL_CONF`` to an invalid path **before** you load any OpenSSL libraries:

```
$ python3 -c "import ssl; print(ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT).maximum_version)"
TLSVersion.TLSv1_3
$ OPENSSL_CONF="/invalid" python -c "import ssl; print(ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT).maximum_version)"
TLSVersion.MAXIMUM_SUPPORTED
```
