### ISSUE TITLE
1.26.7: sphinx errors

### ISSUE THREAD

**Issue by kloczek** [urllib3/urllib3#2507]
### Subject
Looks like sphinx on rendering documentation hows some errors. However despite those errors it finishes with exit 0

### Environment

Describe your environment.
```console
OS Linux-5.14.17-301.fc35.x86_64-x86_64-with-glibc2.34
Python 3.8.12
urllib3 1.26.7
```
sphinx 4.3.1
### Steps to Reproduce
- `python3 -sBm build -w`
- `python3 setup.py build_sphinx -b man --build-dir build/sphinx`

### Expected Behavior
sphinx should render documentation without errors or warnings

### Actual Behavior
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
/usr/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'provides-extra' will not be supported in future versions. Please use the underscore name 'provides_extra' instead
  warnings.warn(
/usr/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'requires-dist' will not be supported in future versions. Please use the underscore name 'requires_dist' instead
  warnings.warn(
running build_sphinx
Running Sphinx v4.3.1
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 21 added, 0 changed, 0 removed
reading sources... [100%] v2-roadmap
WARNING: autodoc: failed to import class 'BrotliDecoder' from module 'urllib3.response'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 448, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'urllib3.response' has no attribute 'BrotliDecoder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 332, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2780, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 464, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: BrotliDecoder

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-urllib3.3 { v2-roadmap sponsors user-guide advanced-usage reference/index reference/urllib3.poolmanager reference/urllib3.connectionpool reference/urllib3.connection reference/urllib3.exceptions reference/urllib3.response reference/urllib3.fields reference/urllib3.request reference/urllib3.util reference/contrib/index reference/contrib/appengine reference/contrib/ntlmpool reference/contrib/pyopenssl reference/contrib/securetransport reference/contrib/socks contributing } done
build succeeded, 1 warning.
```

**Comment by sethmlarson** [comment]
We have a file who's sole purpose is to describe how to build our docs at `readthedocs.yml`.

I've warned you multiple times in the past to not waste maintainer time debugging setups that are clearly incorrect. In the interest of protecting maintainer time and patience you will lose the ability to open issues on GitHub.
