### ISSUE TITLE
Importing urllib3 changes behavior of hypercorn+ASGI app

### ISSUE THREAD

**Issue by jmwielandt** [urllib3/urllib3#2588]
### Subject

Importing urllib3 destroys my hypercorn ASGI.

### Environment

- OS Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
- Python 3.10.4
- urllib3 1.26.9

### Steps to Reproduce

```py
import urllib3  # imported by requests

import asyncio
import signal

from fastapi import FastAPI
from hypercorn.asyncio import serve
from hypercorn.config import Config


app = FastAPI()


@app.get("/ping")
async def ping():
    return "pong"


def main():
    signal.signal(signal.SIGINT, signal.SIG_DFL)  # just to avoid horrible traceback on ctrl+c
    loop = asyncio.new_event_loop()
    cfg = Config()
    cfg.bind = ":7999"
    loop.create_task(serve(app, cfg, shutdown_trigger=lambda: asyncio.Future()))
    print("running! http://localhost:7999/ping")
    loop.run_forever()


if __name__ == "__main__":
    main()
```

Call `localhost:7999/ping` on your browser and see the console output. Call it again (F5).

### Expected Behavior

Comment the urllib3 import line. Now run the code again and call the endpoint: that's what should happend.

### Actual Behavior

```
running! http://localhost:7999/ping
[2022-03-29 09:52:41 -0300] [562] [INFO] Running on http://0.0.0.0:7999 (CTRL + C to quit)
Exception ignored in: <coroutine object serve at 0x7f6994fd8eb0>
Traceback (most recent call last):
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 168, in worker_serve
    gathered_tasks.exception()
asyncio.exceptions.InvalidStateError: Exception is not set.
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<serve() done, defined at /home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/__init__.py:11> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Lifespan.handle_lifespan at 0x7f6994fd8f90>
Traceback (most recent call last):
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py", line 32, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/utils.py", line 247, in invoke_asgi
    await app(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/routing.py", line 645, in __call__
    await self.lifespan(scope, receive, send)
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/routing.py", line 628, in lifespan
    await send({"type": "lifespan.shutdown.failed", "message": exc_text})
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py", line 87, in asgi_send
    raise LifespanFailureError("shutdown", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in shutdown. 'Traceback (most recent call last):
  File "/home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/starlette/routing.py", line 624, in lifespan
    await receive()
GeneratorExit
'
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Lifespan.handle_lifespan() done, defined at /home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py:28> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<raise_shutdown() done, defined at /home/josew/.local/share/virtualenvs/minitest-fastapi-hypercorn-SL-o-K9Y/lib/python3.10/site-packages/hypercorn/utils.py:197> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.10/asyncio/tasks.py:720]>
```

**Comment by jmwielandt** [comment]
The issue must be with hypercorn.

```py
import urllib3  # imported by requests

import asyncio
import signal

from fastapi import FastAPI
from quart import Quart

from hypercorn.asyncio import serve
from hypercorn.config import Config


# app = FastAPI()
app = Quart(__name__)


# @app.get("/ping")
@app.route("/ping", ["GET"])
async def ping():
    return "pong"


def main():
    signal.signal(signal.SIGINT, signal.SIG_DFL)  # just to avoid horrible traceback on ctrl+c
    loop = asyncio.new_event_loop()
    cfg = Config()
    cfg.bind = ":7999"
    loop.create_task(serve(app, cfg, shutdown_trigger=lambda: asyncio.Future()))
    print("running! http://localhost:7999/ping")
    loop.run_forever()


if __name__ == "__main__":
    main()
```


```
running! http://localhost:7999/ping
[2022-03-29 12:23:15 -0300] [1157] [INFO] Running on http://0.0.0.0:7999 (CTRL + C to quit)
Exception ignored in: <coroutine object serve at 0x7f35a4d0f6f0>
Traceback (most recent call last):
  File "/home/josew/python/src/example.com/minitest-fastapi-hypercorn/venv/lib/python3.10/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "/home/josew/python/src/example.com/minitest-fastapi-hypercorn/venv/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 168, in worker_serve
    gathered_tasks.exception()
asyncio.exceptions.InvalidStateError: Exception is not set.
Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<serve() done, defined at /home/josew/python/src/example.com/minitest-fastapi-hypercorn/venv/lib/python3.10/site-packages/hypercorn/asyncio/__init__.py:11> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Lifespan.handle_lifespan() done, defined at /home/josew/python/src/example.com/minitest-fastapi-hypercorn/venv/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py:28> wait_for=<Future cancelled>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<raise_shutdown() done, defined at /home/josew/python/src/example.com/minitest-fastapi-hypercorn/venv/lib/python3.10/site-packages/hypercorn/utils.py:197> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[gather.<locals>._done_callback() at /usr/lib/python3.10/asyncio/tasks.py:720]>
```

**Comment by sethmlarson** [comment]
Very interesting! I'm able to reproduce the issue you describe.

**Comment by sethmlarson** [comment]
@jmwielandt Removing the `import fastapi` also seems to work?

**Comment by sethmlarson** [comment]
So just given how this issue looks there's something weird happening with side-effects somewhere. Could be in urllib3, hypercorn, fastapi, or some other module. I don't think we're going to keep this open as an issue until we can point to a very specific thing that urllib3 is doing that's causing this. Without that there's nothing to go on here, let us know if you figure out anything more specific.
