### ISSUE TITLE
SSLError with Subject Alternative Name (SAN)

### ISSUE THREAD

**Issue by motod** [urllib3/urllib3#2593]
We have an internal web page, which has a certificate with a CN like 'internal-page.com' and an SAN like 'page.com'

Connecting to the CN works without problems, for the SAN, which i am forced to use, i get a SSLError ( see bottom). 

Can you confim problems connecting to a SAN ?

### Environment

OS Linux-4.19.0-18-amd64-x86_64-with-debian-10.12
Python 3.7.3
urllib3 1.26.9

### Steps to Reproduce

import urllib3
import certifi

url = 'https://page.com'  # just an example, no public access to our internal page

http = urllib3.PoolManager(ca_certs=certifi.where())
resp = http.request('GET', url)

### Actual Behavior

```
Traceback (most recent call last):
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    **response_kw
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    **response_kw
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    **response_kw
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/django/.local/share/virtualenvs/test-bw5BkiAG/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='page.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1056)')))

```

**Comment by pquentin** [comment]
This does not appear to be a urllib3 bug, it's OpenSSL that cannot verify the certificate. Can you try to reproduce with `openssl s_client -connect page.com:443`?

What usually happens though in corporate environments is that the root certificate is not public, so `certifi.where()` won't include it. Here is how to check that with Firefox: https://support.mozilla.org/en-US/kb/secure-website-certificate

**Comment by pquentin** [comment]
Unfortunately without having a way to reproduce your issue I don't know what can be done. urllib3 uses the Python standard library that uses OpenSSL under the hood.

Also, I wrote a test to prove that urllib3 handles SAN correctly even with CN is different:

```python3
diff --git a/test/conftest.py b/test/conftest.py
index 656493a7..3eb0c611 100644
--- a/test/conftest.py
+++ b/test/conftest.py
@@ -113,6 +113,16 @@ def no_san_server_with_different_commmon_name(tmp_path_factory):
         yield cfg
 
 
+@pytest.fixture()
+def san_server_with_different_commmon_name(tmp_path_factory):
+    tmpdir = tmp_path_factory.mktemp("certs")
+    ca = trustme.CA()
+    server_cert = ca.issue_cert(u"localhost", common_name=u"example.com")
+
+    with run_server_in_thread("https", "localhost", tmpdir, ca, server_cert) as cfg:
+        yield cfg
+
+
 @pytest.fixture
 def no_san_proxy(tmp_path_factory):
     tmpdir = tmp_path_factory.mktemp("certs")
diff --git a/test/with_dummyserver/test_https.py b/test/with_dummyserver/test_https.py
index 2f3a9651..eeb615b3 100644
--- a/test/with_dummyserver/test_https.py
+++ b/test/with_dummyserver/test_https.py
@@ -887,6 +887,17 @@ class TestHTTPS_NoSAN:
                 https_pool.request("GET", "/")
             assert isinstance(cm.value.reason, SSLError)
 
+    def test_san_with_different_common_name(
+        self, san_server_with_different_commmon_name
+    ):
+        with HTTPSConnectionPool(
+            san_server_with_different_commmon_name.host,
+            san_server_with_different_commmon_name.port,
+            cert_reqs="CERT_REQUIRED",
+            ca_certs=san_server_with_different_commmon_name.ca_certs,
+        ) as https_pool:
+            https_pool.request("GET", "/")
+
 
 class TestHTTPS_IPV4SAN:
     def test_can_validate_ip_san(self, ipv4_san_server):
```


Can you share the certificate chain? Have you double checked there's no typo in your SAN?
