### ISSUE TITLE
Connect timeout does not apply to underlying socket when reusing a connection from the pool

### ISSUE THREAD

**Issue by Ryangwaite** [urllib3/urllib3#2645]
### Subject

When making an HTTP(s) request to a host for which a connection has already been established, this connection is reused from the pool however the timeout provided is only applied to the HTTPSConnection/HTTPConnection object but not it's underlying socket (the original requests timeout remains). Therefore, if the initial request has a short timeout and a subsequent request is initiated that happens to take more time than the initial, the following error will be raised in accordance with the original requests timeout:

```
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError('The write operation timed out'))
```
Note this bug applies to HTTPConnections and HTTPSConnections using the stdlib SSLContext backend but not HTTPSConnections using the PyOpenSSLContext backend.

### Environment
OS: OS Linux-5.4.0-120-generic-x86_64-with-glibc2.31
Python: 3.10.5
urllib3: main (f9c7434)

The docker-compose environment to reliably reproduce this in can be found [here](https://github.com/Ryangwaite/urllib3-docker-dev-env).

### Steps to Reproduce

```python
import time
import urllib3
from urllib3.util import Timeout

TOKEN = "uploadtoken"
BASE_URL = "http://upload-server"
# BASE_URL = "https://upload-server"  # Fails for HTTPS too when using stdlib SSLContext but not PyOpenSSLContext

http = urllib3.PoolManager(cert_reqs='CERT_NONE')

# 1. Seed the timeout on the conn
r = http.request("GET", f"{BASE_URL}/files/test.txt?token={TOKEN}", timeout=Timeout(connect=5, read=6))

# 2. Upload file that takes >5 seconds to complete
# 500MB file at 500mbps bandwidth uploads in ~10.5s with the following code
with open("/var/data-for-upload/500MB.bin") as fp:
    file_data = fp.read()
upload_start = time.time()
try:
    r = http.request("POST", f"{BASE_URL}/upload?token={TOKEN}", fields={"file": ("500MB.bin", file_data)}, timeout=15)
finally:
    print(f"Upload request finished in {time.time() - upload_start:.3f} seconds")

```

### Expected Behavior

For the scenario above, the second request should succeed and be bounded by its 15s timeout.

And the behaviour of the stdlib SSLContext and PyOpenSSLContext backends should match.

### Actual Behavior

The second request fails with:
```
Upload request finished in 6.317 seconds
Traceback (most recent call last):
  File "/home/urllib3/src/urllib3/connectionpool.py", line 727, in urlopen
    httplib_response = self._make_request(
  File "/home/urllib3/src/urllib3/connectionpool.py", line 433, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/urllib3/src/urllib3/connection.py", line 309, in request
    super().request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1076, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.10/http/client.py", line 998, in send
    self.sock.sendall(data)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bug-bait-simple.py", line 22, in <module>
    r = http.request("POST", f"{BASE_URL}/upload?token={TOKEN}", fields={"file": ("500MB.bin", file_data)}, timeout=15)
  File "/home/urllib3/src/urllib3/_request_methods.py", line 116, in request
    return self.request_encode_body(
  File "/home/urllib3/src/urllib3/_request_methods.py", line 216, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/urllib3/src/urllib3/poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/urllib3/src/urllib3/connectionpool.py", line 794, in urlopen
    retries = retries.increment(
  File "/home/urllib3/src/urllib3/util/retry.py", line 467, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/urllib3/src/urllib3/util/util.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/urllib3/src/urllib3/connectionpool.py", line 727, in urlopen
    httplib_response = self._make_request(
  File "/home/urllib3/src/urllib3/connectionpool.py", line 433, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/urllib3/src/urllib3/connection.py", line 309, in request
    super().request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1076, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.10/http/client.py", line 998, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError('timed out'))
```
Notice that the exception was raised 6.317 seconds after starting which is equal to the read timeout of the initial request + some overhead.

The request succeeds when using HTTPS and the PyOpenSSLContext backend whereas the same error as above is raised when using HTTPS and the stdlib SSLContext backend.

**Comment by nickwilliams-zaxiom** [comment]
@SethMichaelLarson, I see that this has been fixed, but was not included in 1.26.13. This issue is currently affecting me as well. Is there a 1.26.x version in which this bug fix will be included? Or will we have to wait for 2.x? Thanks.

**Comment by sethmlarson** [comment]
@nickwilliams-zaxiom If you could submit a backport PR we can discuss including it as a bug fix for that release stream.

**Comment by nickwilliams-zaxiom** [comment]
@sethmlarson, I have submitted the PR as requested. I have a comment in there about the GH action failures as well. Let me know how you'd like me to proceed. We'll move any discussion there. Thanks!
