### ISSUE TITLE
Sporadic SSLZeroReturnError issue

### ISSUE THREAD

**Issue by drcongo** [urllib3/urllib3#2758]
### Subject

I recently migrated a site over to a new server, from Ubuntu 20.04 / Python 3.8.x to Ubuntu 22.04 / Python 3.10.4 and have started seeing errors in the uWSGI log reporting `SSLZeroReturnError`s when trying to send an exception to our exception catcher [Bugsnag](https://github.com/bugsnag/bugsnag-python). The fact that this throws an exception then obviously triggers a loop where it tries to send that failure too.

```
2022-10-29 11:25:57,577 - [bugsnag] ERROR - Notifying Bugsnag failed HTTPSConnectionPool(host='notify.bugsnag.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
Traceback (most recent call last):
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/www/app/.venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/srv/www/app/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='notify.bugsnag.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

During handling of the above exception, another exception occurred:
```

Some exception reports _are_ making it through to Bugsnag which makes this really puzzling to try to solve as I've no lead on where to start looking. There's a _slight_ chance it's a bug in urllib3, but if I'm on entirely the wrong path please feel free to close this, though any pointers on what the right path might be would be really appreciated.

This is happening on a high traffic production server, which also somewhat limits me in what level of debugging and tracing I'm able to do.

### Environment

```
OS Linux-5.15.0-48-generic-x86_64-with-glibc2.35 (Ubuntu 22.04 VM on Digital Ocean)
Python 3.10.4
urllib3 1.26.10
```

### Steps to Reproduce

Sadly I have no idea.

### Expected Behavior

I would expect roughly all SSL requests to notify.bugsnag.com to make it through

### Actual Behavior

Some make it, some don't, the ones that don't trigger a loop of failures.

**Comment by drcongo** [comment]
Actually, I think I may actually have solved this. I fixed one specific exception that was getting through to Bugsnag and in doing so realised that that exception could get triggered up to 30 times on a single request, so the application was then trying to send a whole load of notifications to bugsnag all at once. Stopping it from doing that seems to have stopped the SSL errors.

I'll close this, but leave this info here for anyone arriving by search.
