### ISSUE TITLE
"Usage" example at top of docs raises MaxRetryError

### ISSUE THREAD

**Issue by brandon-rhodes** [urllib3/urllib3#28]
The "Getting Started" section of the documentation suggests this simple test:

``` python
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://google.com/')
```

But actually running this code results in an exception:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    r = http.request('GET', 'http://www.google.com/')
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/request.py", line 65, in request
    **urlopen_kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/request.py", line 78, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 113, in urlopen
    return self.urlopen(method, e.new_url, **kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 113, in urlopen
    return self.urlopen(method, e.new_url, **kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 113, in urlopen
    return self.urlopen(method, e.new_url, **kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 113, in urlopen
    return self.urlopen(method, e.new_url, **kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 109, in urlopen
    return conn.urlopen(method, url, **kw)
  File "/home/brandon/v/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 309, in urlopen
    raise MaxRetryError(url)
urllib3.exceptions.MaxRetryError: Max retries exceeded for url: http://www.google.com/
```

The reason is that each attempt to make a connection is dying with `HostChangedError` because the `is_same_host()` method in `connectionpool.py` is getting back the tuple `('http', 'www.google.com', None)` from `get_host(url)` but the slightly different tuple `('http', 'www.google.com', 80)` when it combines `self.scheme` with `self.host` and `self.port`.

Attempting the test with the URL `http://google.com:80/` also fails because a first successful request is made that redirects to `http://www.google.com/` which then dies as well with the `None != 80` problem.

Only a test with the URL `http://www.google.com:80/` succeeds, because only in that case is the explicit port number present to make `is_same_host()` succeed, and no subsequent redirect occurs to break things.

It looks like either `get_host()` needs to throw in the port `80` when building its tuple, or — if that would ruin the purity and usefulness of that function — the `is_same_host()` function needs to detect the `None` port number coming back from `get_host()` and upgrade it to 80 or 443 as appropriate.

Or: is the problem that the `self.port` that `is_same_host()` is grabbing used to have the value `None` as well, and it's the port having the value `80` so early in the process that is the problem here?

If more experienced project members could point me in the right direction here, I would be happy to contribute a patch and pull request. I could even add a test for the usage example in the documentation, so that it stays working. :) Thanks for your work on urllib3!

**Comment by amitcs100** [comment]
I am seeing this error with urllib3==1.26.9 as well.
