### ISSUE TITLE
Fix documentation build on 1.26.x branch

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2826]
See: https://readthedocs.org/projects/urllib3/builds/18709688/

Looks like an issue with pyOpenSSL?

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    args.pdb)
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/sphinx/application.py", line 219, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/sphinx/builders/linkcheck.py", line 18, in <module>
    from requests import Response
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/requests/__init__.py", line 49, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/OpenSSL/crypto.py", line 3232, in <module>
    name="load_pkcs7_data",
TypeError: deprecated() got an unexpected keyword argument 'name'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/urllib3/envs/2825/lib/python3.7/site-packages/OpenSSL/crypto.py", line 3232, in <module>
    name="load_pkcs7_data",
TypeError: deprecated() got an unexpected keyword argument 'name'
```

**Comment by sethmlarson** [comment]
Closed in https://github.com/urllib3/urllib3/pull/2827
