### ISSUE TITLE
failure parsing proxy-url

### ISSUE THREAD

**Issue by geertn444** [urllib3/urllib3#2858]
### Subject

When using urllib3 with selenium, i always get crashes on proxy_url parsing.
(no matter which driver i am using, Firefox, Chrome or Edge)
Where does urllib3 get the proxy string ?
I must admin the string looks strange in the end, and i believe this causes the error.
But i have no idea from where this string comes from (i have no HTTP_PROXY env variables)

Traceback (most recent call last):
  File "C:\Hubic\Gitlab\Ansible\gn_automate_cyberark\cyberark.py", line 24, in <module>
    driver = webdriver.Firefox()
  File "C:\Python3\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 194, in __init__
    executor = FirefoxRemoteConnection(
  File "C:\Python3\lib\site-packages\selenium\webdriver\firefox\remote_connection.py", line 27, in __init__
    super().__init__(remote_server_addr, keep_alive, ignore_proxy=ignore_proxy)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 183, in __init__
    self._conn = self._get_connection_manager()
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 154, in _get_connection_manager
    return urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args)
  File "C:\Python3\lib\site-packages\urllib3\poolmanager.py", line 478, in __init__
    proxy = parse_url(proxy_url)
  File "C:\Python3\lib\site-packages\urllib3\util\url.py", line 397, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://host001.company.com:800;PROXY

### Environment

OS Windows-10-10.0.19042-SP0
Python 3.9.5
urllib3 1.26.13
selenium                  4.7.2

### Steps to Reproduce

happens during driver initialisation

driver = webdriver.Firefox()

### Expected Behavior

Also, setting option "--no-proxy-server" doesn't help.

### Actual Behavior

What happens instead.
You may attach logs, packet captures, etc.

**Comment by sigmavirus24** [comment]
From your stack trade

```
File "C:\Python3\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 183, in init
self._conn = self._get_connection_manager()
File "C:\Python3\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 154, in _get_connection_manager
return urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args
```

**Comment by geertn444** [comment]
ok, so i checked remote_connection.py and it does come from my environment
import os
print(os.environ.get("HTTP_PROXY"))

http://host001.company.com:800;PROXY

so i will fix that string first. thx
