### ISSUE TITLE
Incorrectly strips trailing dot from absolute hostnames, causing MaxRetryError

### ISSUE THREAD

**Issue by zhanpon** [urllib3/urllib3#2873]
### Subject

Same issue as https://github.com/curl/curl/issues/8290 and https://github.com/psf/requests/issues/6131.

### Environment

```
OS macOS-12.6.2-x86_64-i386-64bit
Python 3.11.1
urllib3 2.0.0a2
```

### Steps to Reproduce

```python
import logging
import urllib3

logging.basicConfig(level=logging.DEBUG)
urllib3.request("HEAD", "http://pyropus.ca./")
```

### Expected Behavior

A 200 response after one redirect.

### Actual Behavior

Raises a `MaxRetryError`:

<details>
<summary>log</summary>

```
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): pyropus.ca.:80
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/zhanpon/tmp/foo.py", line 5, in <module>
    urllib3.request("HEAD", "http://pyropus.ca./")
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/__init__.py", line 151, in request
    return _DEFAULT_POOL.request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 433, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 547, in _make_request
    log.debug(
Message: '%s://%s:%s "%s %s %s" %s'
Arguments: ('http', 'pyropus.ca.', 80, 'HEAD', '/', 'HTTP/1.1', 301, 0)
DEBUG:urllib3.util.retry:Incremented Retry for (url='http://pyropus.ca./'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
INFO:urllib3.poolmanager:Redirecting http://pyropus.ca./ -> https://pyropus.ca./
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pyropus.ca.:443
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/zhanpon/tmp/foo.py", line 5, in <module>
    urllib3.request("HEAD", "http://pyropus.ca./")
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/__init__.py", line 151, in request
    return _DEFAULT_POOL.request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 433, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 547, in _make_request
    log.debug(
Message: '%s://%s:%s "%s %s %s" %s'
Arguments: ('https', 'pyropus.ca.', 443, 'HEAD', '/', 'HTTP/1.1', 301, 0)
DEBUG:urllib3.util.retry:Incremented Retry for (url='https://pyropus.ca./'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
INFO:urllib3.poolmanager:Redirecting https://pyropus.ca./ -> https://pyropus.ca./
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/zhanpon/tmp/foo.py", line 5, in <module>
    urllib3.request("HEAD", "http://pyropus.ca./")
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/__init__.py", line 151, in request
    return _DEFAULT_POOL.request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 433, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 547, in _make_request
    log.debug(
Message: '%s://%s:%s "%s %s %s" %s'
Arguments: ('https', 'pyropus.ca.', 443, 'HEAD', '/', 'HTTP/1.1', 301, 0)
DEBUG:urllib3.util.retry:Incremented Retry for (url='https://pyropus.ca./'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
INFO:urllib3.poolmanager:Redirecting https://pyropus.ca./ -> https://pyropus.ca./
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/zhanpon/tmp/foo.py", line 5, in <module>
    urllib3.request("HEAD", "http://pyropus.ca./")
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/__init__.py", line 151, in request
    return _DEFAULT_POOL.request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 433, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 547, in _make_request
    log.debug(
Message: '%s://%s:%s "%s %s %s" %s'
Arguments: ('https', 'pyropus.ca.', 443, 'HEAD', '/', 'HTTP/1.1', 301, 0)
urllib3.exceptions.ResponseError: too many redirects

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhanpon/tmp/foo.py", line 5, in <module>
    urllib3.request("HEAD", "http://pyropus.ca./")
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/__init__.py", line 151, in request
    return _DEFAULT_POOL.request(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 476, in urlopen
    return self.urlopen(method, redirect_location, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 463, in urlopen
    retries = retries.increment(method, url, response=response, _pool=conn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhanpon/tmp/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 505, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pyropus.ca.', port=443): Max retries exceeded with url: https://pyropus.ca./ (Caused by ResponseError('too many redirects'))
```

</details>

**Comment by nateprewitt** [comment]
Given the age of this and that we don't have a response, I wanted to bring the feedback from https://github.com/psf/requests/issues/7209 here.

It appears this domain has been reported as not working as expected across multiple HTTP tooling ecosystems. What it's expecting seems to conflict with SNI provisions for TLS and urllib3 is inline with curl, aiohttp, and other tooling. I would propose we close this as an issue with the host unless there's a clear indication of incorrect behavior.

Edit: I may have spoken too soon. I found https://github.com/curl/curl/commit/2ab1aff8b96017e1b8d902f4b5dcda6e42d75a50 which reverts this behavior in curl, at least partly. It's hard to know what breaks with the reinclusion of the trailing dot by default though.
