### ISSUE TITLE
urllib3.util.ssl_match_hostname.CertificateError: hostname '10.151.225.49' doesn't match either of 'security-master', '10.151.225.49', 'security-master.default.svc.cluster.local'

### ISSUE THREAD

**Issue by dcvtruong** [urllib3/urllib3#2912]
### Subject

The IP in comparison is the same but does not from urllib3.  The curl command works fine.

### Environment

Describe your environment.
urllib3              1.26.9

### Expected Behavior

Handshake should be successful for host 10.151.225.49

### Actual Behavior

What happens instead.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/util/ssl_match_hostname.py", line 150, in match_hostname
    raise CertificateError(
urllib3.util.ssl_match_hostname.CertificateError: hostname '10.151.225.49' doesn't match either of 'security-master', '10.151.225.49', 'security-master.default.svc.cluster.local'

**Comment by sethmlarson** [comment]
Could you examine the certificate and give the entire `subjectAltName` field in this issue? I'm wondering if this is an issue with how we verify IP addresses? If possible could you also post a minimum reproductive example of the code you're using the send the request?

**Comment by dcvtruong** [comment]
Here's the infos for the ```subjectAltName':
```
            X509v3 Subject Alternative Name: 
                DNS:security-master, DNS:20.157.223.40, DNS:security-master.elk.svc.cluster.local
            X509v3 Basic Constraints: 
                CA:FALSE
```

**Comment by sethmlarson** [comment]
Interesting, does the issue occur if the IP address is in an "IP" name instead of a "DNS" name?

**Comment by sethmlarson** [comment]
Going to close since there's no additional information provided, feel free to comment back and we can reopen.
