### ISSUE TITLE
`test/with_dummyserver/test_no_ssl.py::TestHTTPSWithoutSSL::test_simple` is invalid

### ISSUE THREAD

**Issue by graingert** [urllib3/urllib3#2972]
### Subject

there's supposed to be an SSLError raised but it never gets raised:

https://github.com/urllib3/urllib3/blob/f8fada5ed479e0e6b8440c819632b3a8c040cf65/test/with_dummyserver/test_no_ssl.py#L26-L29

the test should use `with pytest.raises(`

**Comment by graingert** [comment]
note that the actual code raises `ImportError` when the ssl module cannot be found:

```
>>> import sys
>>> sys.modules["ssl"] = None
>>> import urllib3
>>> pool = urllib3.HTTPSConnectionPool("google.com", 443, cert_reqs="NONE")
>>> pool.request("GET", "/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/projects/urllib3/src/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
  File "/home/graingert/projects/urllib3/src/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/graingert/projects/urllib3/src/urllib3/connectionpool.py", line 769, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/graingert/projects/urllib3/src/urllib3/connectionpool.py", line 295, in _get_conn
    return conn or self._new_conn()
  File "/home/graingert/projects/urllib3/src/urllib3/connectionpool.py", line 1056, in _new_conn
    raise ImportError(
ImportError: Can't connect to HTTPS URL because the SSL module is not available.
```

**Comment by graingert** [comment]
this test was invalidated by [`2ec3018` (#1102)](https://github.com/urllib3/urllib3/pull/1102/commits/2ec3018926427c96914373947d06cf32ec7d61fa#r97308148)
