### ISSUE TITLE
Remove of `strict` in 2.0 breaks 3rd party libraries

### ISSUE THREAD

**Issue by sww314** [urllib3/urllib3#3010]
### Subject

The deprecation of `strict` is a breaking change. It is noted in the release notes that it will go away in 2.1, but it is actually remove currently.

See the changes warns but ALSO removes the value: https://github.com/urllib3/urllib3/pull/2267/files

The breaks https://pypi.org/project/CacheControl/0.12.11/ ( at least). 

### Environment

This should not be environment dependent. It depends on which 3rd party libraries it occurs in. 

We see it in Python 3.8. See logs below.

### Expected Behavior

The 2.0 change should not remove strict. Only warn. 

### Actual Behavior

Logs of issues. Reverting to previous version of urllib3 (pre 2.0) solved the problem.

```python
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/auth.py", line 220, in verify_id_token
    return client.verify_id_token(id_token, check_revoked=check_revoked)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_auth_client.py", line 127, in verify_id_token
    verified_claims = self._token_verifier.verify_id_token(id_token)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_token_gen.py", line 293, in verify_id_token
    return self.id_token_verifier.verify(id_token, self.request)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_token_gen.py", line 392, in verify
    verified_claims = google.oauth2.id_token.verify_token(
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/id_token.py", line 133, in verify_token
    certs = _fetch_certs(request, certs_url)
  File "/usr/local/lib/python3.8/site-packages/google/oauth2/id_token.py", line 99, in _fetch_certs
    response = request(certs_url, method="GET")
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_token_gen.py", line 265, in __call__
    return self._delegate(
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/requests.py", line 193, in __call__
    response = self.session.request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 935, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 874, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 809, in _raw_read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 794, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/local/lib/python3.8/site-packages/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/usr/local/lib/python3.8/site-packages/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/usr/local/lib/python3.8/site-packages/cachecontrol/controller.py", line 370, in cache_response
    self._cache_set(
  File "/usr/local/lib/python3.8/site-packages/cachecontrol/controller.py", line 274, in _cache_set
    self.serializer.dumps(request, response, body),
  File "/usr/local/lib/python3.8/site-packages/cachecontrol/serialize.py", line 54, in dumps
    u"strict": response.strict,
AttributeError: 'HTTPResponse' object has no attribute 'strict'
```

**Comment by sww314** [comment]
Since urllib is so widely used - it seems like adding it back and going through with the removal in v2.1.0 is better. 

The dependency is several layers deep for us, and the solution was to pin to an earlier version. 

The fix in `cachecontrol` seems straightforward, but I wonder what other code will be impacted.

**Comment by sigmavirus24** [comment]
`cachecontrol` is nearly unmaintained. I don't believe it has working CI. It depends on a lockfile library that hasn't been maintained in many years. I would strongly recommend against its use at all.

**Comment by sww314** [comment]
I understand. I just looked at the repo, but we do not use `cachecontrol` directly. And it looks like lots of things do currently use it.
According to this there are 33k repos and 500+ projects.

https://github.com/ionrock/cachecontrol/network/dependents?dependent_type=REPOSITORY

And if I read this request correctly, `pip` is one of those dependencies: 
https://github.com/ionrock/cachecontrol/pull/290

As is, the change in will make adoption of urllib3 v2 harder.

**Comment by sethmlarson** [comment]
@pquentin has swayed me that adding back a deprecated hard-coded property for 2.0.x won't hurt us much so we can do so to help adoption of v2, but it will be removed in 2.1.0 so I hope that cachecontrol will adopt a fix.

**Comment by kratsg** [comment]
Impacts betamaxpy/betamax#200 as well.

**Comment by sigmavirus24** [comment]
Pretty sure betamax doesn't implement the full API that urllib3 expects, not a problem with strict based upon that report

**Comment by aaronlanuza** [comment]
We are using urlib3 versions 1.26.4 and 1.25.11 and both are having the  'HTTPResponse' object has no attribute 'strict'. Is there a specific "Pre 2.0" version that does not encounter this error?

**Comment by kratsg** [comment]
i have `urllib3>=1.26.11,<2`

**Comment by pquentin** [comment]
Thanks to new maintainers, cachecontrol 0.13.0 is now compatible with urllib3 2.0! :tada: For that reason, we are probably not going to add this back as we have more urgent things to fix and we are not aware of other libraries relying on `HTTPResponse.strict`.

I'll reopen if we find another compelling case where this is an issue. Thanks everyone.
