### ISSUE TITLE
Module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'

### ISSUE THREAD

**Issue by saisankargochhayat** [urllib3/urllib3#3017]
### Subject
With the latest urllib3 release we are seeing - 
`AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'`
Is this intentional? What is the alternative function?

**Comment by sethmlarson** [comment]
The alias still exists in urllib3 v2.0 but under `urllib3.connection`, not `connectionpool`. The code you're using was working by coincidence because the name was imported and used in a different module. If you fix this code to use `urllib3.connection` then everything will work as expected.

**Comment by xl0** [comment]
I think this also breaks `pytest`:

```
$ python -m pytest
Traceback (most recent call last):
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1067, in pytest_cmdline_parse
    self.parse(args)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1354, in parse
    self._preparse(args, addopts=addopts)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1237, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
    exec(co, module.__dict__)
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/pytest_recording/plugin.py", line 9, in <module>
    from vcr.cassette import Cassette
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/vcr/__init__.py", line 4, in <module>
    from .config import VCR
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/vcr/config.py", line 12, in <module>
    from .cassette import Cassette
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/vcr/cassette.py", line 13, in <module>
    from .patch import CassettePatcherBuilder
  File "/home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/vcr/patch.py", line 41, in <module>
    _VerifiedHTTPSConnection = cpool.VerifiedHTTPSConnection
AttributeError: module 'urllib3.connectionpool' has no attribute 'VerifiedHTTPSConnection'
```

Considering the wide impact, would it be possible to add a workaround to restore the old behavior?

**Comment by xl0** [comment]
@sethmlarson ^^

**Comment by pquentin** [comment]
This does not break pytest, but only vcrpy (you can see it in the traceback if you squint a bit).

Have you tried the latest vcrpy version? It supports urllib3 2.0 if you use Python 3.10 or later.

**Comment by xl0** [comment]
My bad, yes.
