### ISSUE TITLE
Timeout Value Error After Upgrade to `2.0.2`

### ISSUE THREAD

**Issue by tim-corley-bose** [urllib3/urllib3#3023]
### Subject

After upgrading from `1.26.15` to `2.0.2` the following Timeout error is being triggered when running script via a Jenkins job. 

```
Timeout value connect was <object object at 0x109190cb0>, but it must be an int, float or None
```

### Environment

```
OS macOS-12.6.4-x86_64-i386-64bit
Python 3.9.6
urllib3 2.0.2
```

```
Traceback (most recent call last):
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 822, in get_info
     return json.loads(self.jenkins_open(
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 560, in jenkins_open
     return self.jenkins_request(req, add_crumb, resolve_auth).text
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 576, in jenkins_request
     self.maybe_add_crumb(req)
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 373, in maybe_add_crumb
     response = self.jenkins_open(requests.Request(
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 560, in jenkins_open
     return self.jenkins_request(req, add_crumb, resolve_auth).text
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 579, in jenkins_request
     self._request(req))
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/jenkins/__init__.py", line 553, in _request
     return self._session.send(r, **_settings)
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
     r = adapter.send(request, **kwargs)
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/requests/adapters.py", line 483, in send
     timeout = TimeoutSauce(connect=timeout, read=timeout)
   File "/home/jenkins/agent/workspace/my-jenkins-job//lib/python3.9/site-packages/urllib3/util/timeout.py", line 119, in __init__
     self._connect = self._validate_timeout(connect, "connect")
   File "/home/jenkins/agent/workspace/my-jenkins-job/staging/lib/python3.9/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
     raise ValueError(
 ValueError: Timeout value connect was <object object at 0x109190cb0>, but it must be an int, float or None.
```

**Comment by Crola1702** [comment]
Same happening to me with python 3.11.0

**Comment by tim-corley-bose** [comment]
Ok, thank you for pointing to the `python-jenkins` bug report - very helpful!
