### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by Ousret** [urllib3/urllib3#3049]
### Subject

Python 3.12b1 has recently been released. Few issues appeared.

### Deprecations

They are ALL indirect deprecations. that can be ignored in the meantime using:

```
'''default:ast\.([a-zA-Z]+) is deprecated and will be removed:DeprecationWarning''',
'''default:Attribute s is deprecated and will be removed in:DeprecationWarning''',
'''default:datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal in:DeprecationWarning''',
```

The first two are triggered in **pytest** and the last one in python-dateutil.

### References

- https://github.com/pytest-dev/pytest/issues/10977
- https://github.com/dateutil/dateutil/issues/1284

### Errors

Three tests fail consistently.

```
FAILED test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_redirect - assert 500 == 303
 +  where 500 = <urllib3.response.HTTPResponse object at 0x7f9a271f3d30>.status
FAILED test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_cross_host_redirect - Failed: DID NOT RAISE <class 'urllib3.exceptions.MaxRetryError'>
FAILED test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_cross_protocol_redirect - Failed: DID NOT RAISE <class 'urllib3.exceptions.MaxRetryError'>
```

```
Traceback (most recent call last):
  File "/home/runner/work/urllib3/urllib3/test/with_dummyserver/test_proxy_poolmanager.py", line 222, in test_redirect
    assert r.status == 303
AssertionError: assert 500 == 303
 +  where 500 = <urllib3.response.HTTPResponse object at 0x7f9a271f3d30>.status
```

I suspect that the dev server crashed. I'm afraid I don't have any more details for now.

**Comment by Ousret** [comment]
Mmm...

The tests passed locally. Cannot reproduce, this is up to a bad start.

```
platform linux -- Python 3.12.0b1, pytest-7.2.0, pluggy-1.0.0
test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_redirect PASSED
...
```

Ubuntu 22.04 lts.

**Comment by graingert** [comment]
I can reproduce the `test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_redirect` failure locally I suspect this is a Python 3.12 bug

**Comment by graingert** [comment]
It seems the failure is quite brittle, when running the proxy server directly without pytest it works correctly:

```python
import asyncio
import sys

from tornado import httpserver, ioloop, web
from dummyserver.server import run_loop_in_thread, run_tornado_app
from dummyserver.proxy import ProxyHandler
from dummyserver.handlers import TestingApp
from urllib3.poolmanager import ProxyManager, proxy_from_url


def main():
    with run_loop_in_thread() as io_loop:

        async def run_app():
            app = web.Application([(r".*", TestingApp)])
            http_server, http_port = run_tornado_app(app, None, "http", "localhost")
            proxy_app = web.Application([(r".*", ProxyHandler)])
            proxy_server, proxy_port = run_tornado_app(
                proxy_app, None, "http", "localhost"
            )
            return http_port, proxy_port

        http_port, proxy_port = asyncio.run_coroutine_threadsafe(
            run_app(), io_loop.asyncio_loop
        ).result()
        http_url = f"http://localhost:{http_port}"
        proxy_url = f"http://localhost:{proxy_port}"

        with proxy_from_url(proxy_url) as http:
            r = http.request(
                "GET",
                f"{http_url}/redirect",
                fields={"target": f"{http_url}/"},
                redirect=False,
            )
            breakpoint()
            assert r.status == 303, f"status was {r.status}"


sys.exit(main())
```

**Comment by Ousret** [comment]
Interesting... we both tried and got a different result from the exact Python beta.
Could you share the difference? _e.g. what makes it (the proxy) return 500_

**Comment by graingert** [comment]
this fails when running with coverage:

```python
import asyncio

async def inner():
    loop = asyncio.get_running_loop()
    fut = loop.create_future()
    loop.call_later(0.1, fut.set_exception, Exception())
    try:
        await fut
    except Exception:
        print("good")

async def main():
    await inner()

asyncio.run(main())
```

```
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/coverage run -m demo
Traceback (most recent call last):
  File "/home/graingert/projects/urllib3/demo.py", line 15, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/graingert/projects/urllib3/demo.py", line 13, in main
    await inner()
Exception
 ✘  graingert@conscientious  ~/projects/urllib3   py3-12-debug ± vim demo.py 
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± python -m demo
good
```

**Comment by Ousret** [comment]
In fact, yes, I was not using coverage in the try-to-reproduce.
Nicely found @graingert Eventually led to cpython.
