### ISSUE TITLE
HttpHeaderDict does not support bytes object

### ISSUE THREAD

**Issue by tushar5526** [urllib3/urllib3#3072]
### Subject

Passing bytes as the value in `HttpHeaderDict` is not handled completely. 

### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import ssl
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print(ssl.OPENSSL_VERSION)
print("urllib3", urllib3.__version__)
```
```
OS Linux-5.19.0-43-generic-x86_64-with-glibc2.35
Python 3.10.6
OpenSSL 3.0.2 15 Mar 2022
```

### Steps to Reproduce

```
import urllib3

headers = urllib3.HTTPHeaderDict()
encoded_data = "Schönefeld/1.18.0".encode('latin-1')

headers['user-agent'] = encoded_data
headers['user-agent']
print(headers['user-agent'])
```

### Expected Behavior

You can access bytes objects passed in headers. 

### Actual Behavior
Errors out with this
```
Traceback (most recent call last):
  File "/home/tushar55/test.py", line 8, in <module>
    headers['user-agent']
  File "/home/tushar55/projects/urllib3/src/urllib3/_collections.py", line 260, in __getitem__
    return ", ".join(val[1:])
TypeError: sequence item 0: expected str instance, bytes found

```

Bytes are not handled - https://github.com/urllib3/urllib3/blob/main/src/urllib3/_collections.py#L257 , https://github.com/urllib3/urllib3/blob/main/src/urllib3/_collections.py#L426 

Using bytes as keys has some level of handling - https://github.com/urllib3/urllib3/blob/main/src/urllib3/_collections.py#L251

Found this issue while going through #3047

**Comment by panzer** [comment]
@tushar5526 Are you looking for someone to contribute a fix? If so, I can look into it.

**Comment by tushar5526** [comment]
Hi @ panzer, this issue is still not confirmed. The core maintainers have not triaged this one yet. Let's wait for them :)

**Comment by panzer** [comment]
@tushar5526 I'm looking through some old issues and pull requests. It seems the maintainers do not do much triage. I'm willing to look work on this issue. If we want to wait for a maintainer to review, let's get in touch directly with that person

**Comment by sethmlarson** [comment]
@tushar5526 @panzer Thanks for the patience, it would be great to have support for bytes as values in `HTTPHeaderDict`. I'm not sure how exactly that would work internally, maybe you have some ideas :)

**Comment by Kausha3** [comment]
I am picking this up. I will keep the scope to HTTPHeaderDict bytes values, add focused regression tests for setting and reading byte-valued headers, and avoid changing request serialization behavior beyond the collection access paths.

**Comment by Kausha3** [comment]
I found active PRs already open for this issue after checking the PR search results, including #5006. I will not duplicate that work. Leaving this note so maintainers and other contributors have a clear handoff.

**Comment by dkx955** [comment]
@sethmlarson, on your 2024 question about how this would work internally, and @pquentin's "whatever the right thing is" in #3279 — I tried to answer that part by measuring rather than arguing, and found something that sits underneath this issue.

**On unmodified main, urllib3 already sends the same header value as different octets depending on the protocol version.** No bytes involved, plain `str`:

| path | `"Schönefeld/1.18.0"` on the wire |
| --- | --- |
| HTTP/1.1 (`http.client`, latin-1) | `536368 f6 6e6566656c642f312e31382e30` |
| HTTP/2 (`http2/connection.py`, bare `.encode()` = UTF-8) | `536368 c3b6 6e6566656c642f312e31382e30` |

An ASCII control is byte-identical on both paths, so this is the codec and not my measuring setup. `"→"` is worse than a mismatch: it raises `UnicodeEncodeError` over HTTP/1.1 and is quietly sent as UTF-8 over HTTP/2.

**Why this matters for bytes values specifically.** The reason "decode bytes to latin-1 on the way in" feels risky is that it looks lossy. It isn't: latin-1 round-trips all 256 byte values exactly, so as long as the encode on the way out is *also* latin-1, `bytes in → bytes on the wire` is the identity. Today that holds for HTTP/1.1 and fails for HTTP/2 — which I think is a large part of why "how would this work internally" has no comfortable answer. Align the two, and the answer becomes small: `HTTPHeaderDict` can store `str`, and a bytes value survives byte-for-byte on both protocols.

I opened #5138 for just the alignment part (two `.encode()` calls, plus tests that fail without the change). It does **not** implement bytes values and does not conflict with the four PRs already open here (#3279, #3792, #5006, #5114) — those all touch `_collections.py`, this one doesn't.

If the alignment is wrong for HTTP/2 for a reason I've missed, then that is worth knowing before any of the `_collections.py` PRs land, because they would inherit the mismatch.

Disclosure: I'm an AI-assisted contributor and say so openly. Not claiming this issue — the measurements are reproducible and I'm happy to hand over the rig (real socket for HTTP/1.1, real h2 frames with HPACK decoding for HTTP/2) to whoever picks it up.
