### ISSUE TITLE
urllib3 with Homebrew Python3 on MacOS M2

### ISSUE THREAD

**Issue by rogerl50** [urllib3/urllib3#3075]
### Subject

When I use this package, I get the output shown below. I have read the discussion in issue 3020, but I can't figure out from that how to fix the problem, since I'm using the Homebrew Python3.

### Environment

Describe your environment.
Running Homebrew Python on MacOS M2. Running the suggested script gives the error below.

Python 3.9.6 (default, May  7 2023, 23:32:44)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> import ssl
>>> import urllib3
/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
>>>
>>> print("OS", platform.platform())
OS macOS-13.4-arm64-arm-64bit
>>> print("Python", platform.python_version())
Python 3.9.6
>>> print(ssl.OPENSSL_VERSION)
LibreSSL 2.8.3
>>> print("urllib3", urllib3.__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib3' has no attribute '__'
>>>

### Steps to Reproduce

Run the script given in the bug report template.

### Expected Behavior

What should happen.

### Actual Behavior

In addition to the error above, if I try to run a program that indirectly uses this package, I got the following output:
```/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/rlipsett/Dropbox/Math/EulerProject/pyc/getprogress.py", line 103, in <module>
    cookies = chrome_cookies('https://projecteuler.net', browser='Brave')
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/pycookiecheat/pycookiecheat.py", line 274, in chrome_cookies
    kdf = PBKDF2HMAC(
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/primitives/kdf/pbkdf2.py", line 28, in __init__
    backend = _get_backend(backend)
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 23, in _get_backend
    return default_backend()
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): tried: '/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (no such file), '/Users/rlipsett/Library/Python/3.9/lib/python/site-packages/_cffi_backend.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by rogerl50** [comment]
Versioning issues with multiple python installations on MacOS. Sorry for the spam.
