### ISSUE TITLE
debug logging in _new_conn has string formating TypeError

### ISSUE THREAD

**Issue by aDrongo** [urllib3/urllib3#3097]
### Subject

Debug logging produces a TypeError when formatting

### Environment

Python 3.8.13 (default, May  3 2022, 21:42:55)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux

### Steps to Reproduce

```
import logging
import json
import sys
import requests

class Filter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        record.msg = json.dumps(record.getMessage())
        return True

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger()
handler = logging.StreamHandler()
handler.addFilter(Filter())
handler.setLevel(logging.DEBUG)
logger.addHandler(handler)

requests.get('http://www.google.com')
```

### Expected Behavior

This should not throw a type error

### Actual Behavior

>>> requests.get('https://www.google.com')
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com:443
<LogRecord: urllib3.connectionpool, 10, /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py, 1003, "Starting new HTTPS connection (%d): %s:%s">
(1, 'www.google.com', 443)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1003, in _new_conn
    log.debug(
Message: '"Starting new HTTPS connection (1): www.google.com:443"'
Arguments: (1, 'www.google.com', 443)

**Comment by aDrongo** [comment]
I'm actually going to close this, after more testing it seems that using record.msg = record.getMessage() is not compatible with this tuple style string formatting, it is not to do with anything different urllib3 is doing, the debug formating urllib3 uses works fine. Thank you.
