### ISSUE TITLE
Handling of idle timeout (aws nat gateway fixed idle timeout of 350 seconds)

### ISSUE THREAD

**Issue by ecerulm** [urllib3/urllib3#3184]
### Context

using a connection pool to a given host where the connection are going through an AWS NAT Gateway which has a fixed idle timeout of 350 seconds. 

The issue is that when a new request is performed after 350 seconds, the connection will error with "Connection reset by peer" (nat gateway will send an explicit RST when trying to send to that connection after the idle timeout) , then it will retry but  the next connection in the pool will also be "reset by peer" (it was idle too). 

I would be nice to have `idle_timeout=349` parameter for PoolManager/ConnectionPool, so that urllib3 will check if the connection has been idle for more than that and discard it before use it.

 I think today ([from comment](https://github.com/urllib3/urllib3/issues/2498#issuecomment-991693743) 
> When a connection is pulled from the pool it's checked to see if the underlying socket is still open and if not the connection is reopened.

The problem with that is the the underlying socket is still open (you will only get the RST from aws nat gateway) after you try to use it. 

So my proposal is is to in addition to check if the underlying socket is still open, to do also a check if the idle_timeout has passed, if it has pass reopen the connection. 

Is it something you currently cannot do?
well, I guess , I can catch the exception (after all the retries) , and drop the whole poolmanager/connectionpool.

Is this related to an existing issue/problem?

Yes, connections via nat gateway have implicit idle timeout and connection are not explicitly reset by nat gateway, they are only resetted when you try to used them. That plays bad with current urllib behavior because it will retry but all connections for that host are "tainted", so it should not try to use them .

### Alternatives

Can you achieve the same result doing it in an alternative way?
Is the alternative considerable?

I guess that will require some error handling and drop the poolmanager/connectionpool and create a new one when this is detected. 

### Duplicate

Has the feature been requested before?
If so, please provide a link to the issue.

#2498 was dismissed on the grounds that it will require a background thread, but I think there is no need for that. This could be done by checking if the idle_timeout has passed when the connection is pulled from the pool and reopening the connection if the timeout has passed.  I guess #2498 was calling for a more explicitly closes the connection after the idle_timeout, but I'm asking more for a "consider idle connection dead after x seconds). 

### Contribution

Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_

**Comment by sethmlarson** [comment]
I could see a feature like this being useful, especially how you describe it with checking a "last known good" time against the `idle_timeout` on the connection pool. Would cut down on the number of unnecessary retries happening as well.

What do other maintainers think about this feature? @pquentin @illia-v

**Comment by illia-v** [comment]
I agree that this can be useful

**Comment by methane** [comment]
For the record, how to reproduce this:

```app.go
// HTTP server with idle_timeout=1s
package main

import (
	"net/http"
	"time"
	"fmt"
	"log"
)

func myHandler(w http.ResponseWriter, r *http.Request) {
	time.Sleep(100 * time.Millisecond)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	fmt.Fprintf(w, "Hello, world!")
}

func main() {
	s := &http.Server{
		Addr:           ":8080",
		Handler:        http.HandlerFunc(myHandler),
		IdleTimeout:    1 * time.Second,
	}
	log.Fatal(s.ListenAndServe())
}
```

```client.py
import requests
import threading
import time
import random
import logging

# logging.basicConfig(
#     level=logging.DEBUG,
#     format='%(asctime)s %(name)s %(levelname)s %(message)s'
# )

url = "http://127.0.0.1:8080"  # app.go

def get():
    session = requests.Session()
    for i in range(1000):
        response = session.get(url)
        response.raise_for_status()
        time.sleep(random.uniform(0.98, 1.0))  # idle for 0.98~1.0s

workers = []

for i in range(100):
    th = threading.Thread(target=get)
    th.start()
    workers.append(th)

for worker in workers:
    worker.join()
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
                             " response")
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
                             " response")
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/Users/inada-n/.local/share/uv/python/cpython-3.13.7-macos-aarch64-none/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inada-n/notes/python/requests_pool/keepalive_requests.py", line 18, in get
    response = session.get(url)
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/inada-n/notes/python/requests_pool/.venv/lib/python3.13/site-packages/requests/adapters.py", line 659, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by ZacWang15** [comment]
What is your current workaround to fix this issue, @ecerulm ? 

Also, I have a question. When the first request is failed, I think it will start a new connection. Why the new connection is still the idle connection in NAT. 
By default, HTTPConnectionPool only keep 1 connection. Shouldn't it create a new connection with the server?

**Comment by edwardpeek-crown-public** [comment]
> Also, I have a question. When the first request is failed, I think it will start a new connection. Why the new connection is still the idle connection in NAT. By default, HTTPConnectionPool only keep 1 connection. Shouldn't it create a new connection with the server?

Speaking for ourselves, we disable automatic retries to handle them in application space, so don't get the new connection patching over this issue.
