### ISSUE TITLE
Error in Kodi after updating urllib3 to version 2.1.0

### ISSUE THREAD

**Issue by burekas7** [urllib3/urllib3#3220]
### Environment
Kodi 20, Windows 10

This is the error I get in one of the addons

**Error Contents: cannot import name 'appengine' from 'urllib3.contrib'**

**from requests.packages.urllib3.contrib import appengine as gaecontrib**

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'ImportError'>
                 Error Contents: cannot import name 'appengine' from 'urllib3.contrib' (D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
                 Traceback (most recent call last):
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\_compat.py", line 48, in <module>
                     from requests.packages.urllib3.contrib import appengine as gaecontrib
                 ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
                 
                 During handling of the above exception, another exception occurred:
                 
                 Traceback (most recent call last):
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\default.py", line 3, in <module>
                     from resources.main import route
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\main.py", line 4, in <module>
                     import resources.lib.common as common
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\common.py", line 4, in <module>
                     import resources.lib.cloudscraper as cloudscraper
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\cloudscraper\__init__.py", line 14, in <module>
                     from resources.lib.requests_toolbelt.utils import dump
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\__init__.py", line 12, in <module>
                     from .adapters import SSLAdapter, SourceAddressAdapter
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\adapters\__init__.py", line 12, in <module>
                     from .ssl import SSLAdapter
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\adapters\ssl.py", line 16, in <module>
                     from .._compat import poolmanager
                   File "D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\plugin.video.idanplus\resources\lib\requests_toolbelt\_compat.py", line 50, in <module>
                     from urllib3.contrib import appengine as gaecontrib
                 ImportError: cannot import name 'appengine' from 'urllib3.contrib' (D:\Program Files (x86)\Kodi v20.1 x64 Nightly\portable_data\addons\script.module.urllib3\lib\urllib3\contrib\__init__.py)
                 -->End of Python script error report<--
```

**Comment by sigmavirus24** [comment]
This was removed in 2.0 https://urllib3.readthedocs.io/en/stable/changelog.html#id10

Please read the changelog before upgrading and confirm your system and it's dependencies are compatible. You should determine what plugin is incompatible and file a bug with them as we will not be adding this back.
