### ISSUE TITLE
urllib3 2.x SSLV3 Alert Handshake Failure for Proxy server with custom certificates

### ISSUE THREAD

**Issue by rsmoorthy** [urllib3/urllib3#3245]
### Subject

With urllib3 version 2.x, while connecting to a https server via a HTTP (not https) proxy that issues custom certificates, We receive a `sslv3 alert handshake failure`. However, the same setup with urllib3 1.26 works fine.

### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import ssl
import urllib3

print("OS", platform.platform())   #  OS Linux-5.15.0-88-generic-x86_64-with-glibc2.36  
                                                           #  (running in container from image python:3.11-slim)
print("Python", platform.python_version()) # Python 3.11.7
print(ssl.OPENSSL_VERSION) # OpenSSL 3.0.11 19 Sep 2023
print("urllib3", urllib3.__version__) # urllib3 2.1.0
```

### Steps to Reproduce

Simple code to reproduce:

```
import urllib3
urllib3.add_stderr_logger()
conn = urllib3.ProxyManager("http://proxy.host:8080", retries=False, cert_reqs="CERT_REQUIRED", ca_certs="/path/to/root_ca.crt")
conn.request("GET", "https://www.google.com")
```

### Expected Behavior

```
2023-12-22 08:53:24,546 DEBUG Added a stderr logging handler to logger: urllib3
2023-12-22 08:53:24,547 DEBUG Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2023-12-22 08:53:24,547 DEBUG Starting new HTTPS connection (1): www.google.com:443
2023-12-22 08:53:25,373 DEBUG https://www.google.com:443 "GET / HTTP/1.1" 200 None
```

### Actual Behavior

```
2023-12-22 08:51:33,154 DEBUG Added a stderr logging handler to logger: urllib3
2023-12-22 08:51:33,155 DEBUG Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2023-12-22 08:51:33,155 DEBUG Starting new HTTPS connection (1): www.google.com:443
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 776, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1045, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//root/pp.py", line 20, in <module>
    conn.request("GET", "https://www.google.com/")
  File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 634, in urlopen
    return super().urlopen(method, url, redirect=redirect, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 444, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 445, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 776, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1045, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)
```

### With urllib3 1.26

If urllib3 is installed with version 1.26, there is no error and the behaviour is as expected.

### Verification from v2.0 Migration Guide

1. `Python version must be 3.7 or later`  -- YES
2. `Removed support for OpenSSL versions older than 1.1.1.`  -- OpenSSL version is 3.x
3. `Changed the default minimum TLS version to TLS 1.2`  -- curl -vv https://www.google.com/ via the same MITM proxy shows TLS 1.2
4. `Removed support for verifying certificate hostnames via commonName, now only subjectAltName is used.` -- curl -vv https://www.google.com/ via the same MITM proxy shows

```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=www.google.com
*  start date: Nov 20 08:09:47 2023 GMT
*  expire date: Feb 12 08:09:46 2024 GMT
*  subjectAltName: host "www.google.com" matched cert's "www.google.com"
*  issuer: DC=LOCAL; DC=<redacted My Company Name>; CN=<redacted - My Company Name>
*  SSL certificate verify ok.
* using HTTP/1.x
```

**Comment by sethmlarson** [comment]
This seems like it's potentially an issue with ciphersuite coverage, try either pointing the two clients at `https://howsmyssl.com/a/check` and seeing the ciphersuite lists and how they differ or using a program like Wireshark to inspect the ClientHello and ServerHello TLS messages. Hope this helps!
