### ISSUE TITLE
IncompleteRead for last 64kb chunk of file, method works on versions before 2.1.0 (have "fix")

### ISSUE THREAD

**Issue by henryjfry** [urllib3/urllib3#3277]
### Subject
I have written a hashing function for files and remote URLS as per the wiki here:

https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Python

And my github:

https://gist.github.com/henryjfry/82c490ca8415a13fd6d388230835e448

Tested on a PI python terminal and a windows Python terminal.
Function works perfectly.

However in kodi the errors are returned:

````
2024-01-11 22:05:10.683 T:4549    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ChunkedEncodingError'>
                                                   Error Contents: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 712, in _error_catcher
                                                       yield
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 833, in _raw_read
                                                       raise IncompleteRead(self._fp_bytes_read, self.length_remaining) ## PATCH
                                                   urllib3.exceptions.IncompleteRead: IncompleteRead(65536 bytes read, 1 more expected)

                                                   The above exception was the direct cause of the following exception:

                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 816, in generate
                                                       yield from self.raw.stream(chunk_size, decode_content=True)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 934, in stream
                                                       data = self.read(amt=amt, decode_content=decode_content)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 877, in read
                                                       data = self._raw_read(amt)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 833, in _raw_read
                                                       raise IncompleteRead(self._fp_bytes_read, self.length_remaining) ## PATCH
                                                     File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
                                                       self.gen.throw(type, value, traceback)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py", line 729, in _error_catcher
                                                       raise ProtocolError(f"Connection broken: {e!r}", e) from e
                                                   urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/script.py", line 35, in <module>
                                                       Main()
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/script.py", line 14, in __init__
                                                       process.start_info_actions(self.infos, self.params)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/resources/lib/process.py", line 1079, in start_info_actions
                                                       next_ep_play(show_title, show_season, show_episode, tmdb)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kwrapper_player.py", line 519, in next_ep_play
                                                       subs_list = subs.get_subtitles_list(meta_info, PTN_download)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 289, in get_subtitles_list
                                                       meta = get_subtitles_meta(VIDEO_META, file_path)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 214, in get_subtitles_meta
                                                       VIDEO_META2 = set_size_and_hash_url(meta=VIDEO_META, filepath=file_path)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 167, in set_size_and_hash_url
                                                       returnedhash, filesize = hashFile_url(filepath)
                                                     File "/home/osmc/.kodi/addons/script.extendedinfo/a4kscrapers_wrapper/subs.py", line 91, in hashFile_url
                                                       for chunk in r.iter_content(chunk_size=1024):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 818, in generate
                                                       raise ChunkedEncodingError(e)
                                                   requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))
                                                   -->End of Python script error report<--

````

So the specific error which breaks the code:

````
 urllib3.exceptions.IncompleteRead: IncompleteRead(65536 bytes read, 1 more expected)
````
 
However the code is requesting only 64kb at the very end of the file, therefore the nuber of bytes are exactly as expected.

I therefore patched the file:
 
````
/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/response.py
````

As per the addon:

https://mirrors.kodi.tv/addons/matrix/script.module.urllib3/script.module.urllib3-2.1.0.zip

As the error:

````
urllib3.exceptions.IncompleteRead: IncompleteRead(65536 bytes read, 1 more expected)
````
 
I believe is (for some reason) counting additional bytes? Therefore where the bytecount is only 1 longer then this confirms the exact lenght?

So my "Fix" is to modify the line:

From 

````
                    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)  
````

TO:

````
                    if self.length_remaining > 1: raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
````

This resolves my error but I am assuming is not anything like a method to be implemented as an actual fix.

### Environment

Describe your environment.
At least, paste here the output of:

```python
import platform
import ssl
import urllib3

print("OS", platform.platform())
print("Python", platform.python_version())
print(ssl.OPENSSL_VERSION)
print("urllib3", urllib3.__version__)
```

Returns on the PI:

````
OS Linux-4.9.269-44-osmc-aarch64-with-glibc2.31
Python 3.9.2
OpenSSL 1.1.1w  11 Sep 2023
urllib3 1.26.5
````

### Steps to Reproduce

The code at the wiki:

https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#Python

And my gist:

https://gist.github.com/henryjfry/82c490ca8415a13fd6d388230835e448

Against a large Mp4 file from a streaming webhost?  I can't provide a RealDebrid link myself as it would register an IP violation if you tried to use it.

### Expected Behavior

The last chunk of the file should report the lenght as 64kb corresponding to what has actually been downloaded.

### Actual Behavior

The header request for only 64kb is correct (as evidenced by the code working 100% correctly for urllib3 1.26.5) but for some reason 2.1.0 wants to count an extra Byte?
And therefore it throws an "IncompleteRead" error when the required chunk has been read.

**Comment by abebeos** [comment]
> Returns on the PI:

Can you post the version info of win and especially kodi?

The 2.* version has breaking changes.

### Potential Solution

* import the working urllib 1.* version on kodi.

**Comment by henryjfry** [comment]
> > Returns on the PI:
> 
> Can you post the version info of win and especially kodi?
> 
> The 2.* version has breaking changes.
> 
> ### Potential Solution
> * import the working urllib 1.* version on kodi.

I agree that downgrading the version of "script.module.urllib3" to this version:

https://mirrors.kodi.tv/addons/matrix/script.module.urllib3/script.module.urllib3-1.26.16+matrix.1.zip

Would be a solution.

But I did attempt to import the non Kodi version of Urllib3 and I couldnt figure out how to replace or otherwise import a system python module from "/usr/lib/python3/dist-packages/urllib3" rather than  "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/"

The issue would be (i think) that "usr" modules in kodi need to be instantiated by an addon and the requests module instantiates the kodi version of  Urllib3.

So my function/addon could call the correct version of urllib3 but the requests module will use whatever version kodi has installed.
Therefore a user would need to choose to downgrade to fix the error (or notice it was never providing a file hash due to an exception error).

Im not so very experienced in python to understand exactly how modules function in the background. Im sure it is possible to make it use the correct version without installing a different addon but i couldnt figure it out myself.

**Comment by abebeos** [comment]
Try this here:

- https://stackoverflow.com/a/6445404

then lookup for similar stuff on the web (the usual drama).

If all fails, wait until a maintainer sees the issue here.

**Comment by abebeos** [comment]
possibly related: https://github.com/urllib3/urllib3/issues/3261

**Comment by henryjfry** [comment]
> possibly related: #3261

Yeah i saw that but I didnt know if the negative bytes being returned were connected to the same issue or not.
Im not really a network/server/internet type guy so bytestreams and correct server responses are not really my bag.

Mine appeared to be an error reported for returning exactly what it was asked to return, so not an error.
Whereas this other issue seemed to be an error handling issue for an error response, so returning the wrong error?

**Comment by abebeos** [comment]
### Reproducer

What you could do to get faster help from a maintainer (or someone else who has the curiosity) :

Reduce this https://gist.github.com/henryjfry/82c490ca8415a13fd6d388230835e448 down to a minimum to trigger the error. Strip everything you can, until only a few lines remain.

**Comment by henryjfry** [comment]
I can reproduce this 100% with files from real-debrid but I cant find an equivalent public link.

The unrestricted real-debrid links are private and any sharing would be an IP violation and I dont want to get banned.
But I cant find a public link itll work with

**Comment by henryjfry** [comment]
So the code to reproduce this with Urllib3 v2.1.0:

````
import requests, tempfile
test_url = 'https://20.download.real-debrid.com/d/XXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXX.mp4'

__64k = 65536
response = requests.head(test_url)
filesize = int(response.headers['content-length'])


if filesize < __64k * 2:
	try: filesize = int(str(response.headers['content-range']).split('/')[1])
	except: pass

file = tempfile.NamedTemporaryFile()
first_64kb = file.name
file = tempfile.NamedTemporaryFile()
last_64kb = file.name

headers = {"Range": 'bytes=0-%s' % (str(__64k))}
r = requests.get(test_url, headers=headers)
with open(first_64kb, 'wb') as f:
	for chunk in r.iter_content(chunk_size=1024): 
		if chunk: # filter out keep-alive new chunks
			f.write(chunk)

if filesize > 0:
	headers = {"Range": 'bytes=%s-%s' % (filesize - __64k, filesize)}

r = requests.get(test_url, headers=headers)
with open(last_64kb, 'wb') as f:
	for chunk in r.iter_content(chunk_size=1024): 
		if chunk: # filter out keep-alive new chunks
			f.write(chunk)
````

**Comment by abebeos** [comment]
Smaller,
test data must be public,
cross-check with other (mp4) data,
cross-check with working library version and mention version number
Ideally use urllib import only

> I can reproduce this 100% with files from real-debrid but I cant find an equivalent public link.

Do non-real-debrid files work?

**Comment by abebeos** [comment]
can you try this with your data?

if it fails, then see to it to make the data available.

```py
import requests

test_url = 'https://www.learningcontainer.com/download/sample-mp4-video-file-download-for-testing/?wpdmdl=2727'

__64k = 65536
response = requests.head(test_url)
filesize = int(response.headers['content-length']); print(filesize)

if filesize < __64k * 2:
	try: filesize = int(str(response.headers['content-range']).split('/')[1])
	except: pass

headers = {"Range": 'bytes=0-%s' % (str(__64k))}; print(headers)
r = requests.get(test_url, headers=headers)

if filesize > 0:
	headers = {"Range": 'bytes=%s-%s' % (filesize - __64k, filesize)}; print(headers)
r = requests.get(test_url, headers=headers)
```

**Comment by abebeos** [comment]
alternative url: https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4

**Comment by abebeos** [comment]
Your reproducer https://gist.github.com/henryjfry/82c490ca8415a13fd6d388230835e448 is not(!) related to `urllib3` (neither directly, nor indirectly), it works on my side without urllib3/requests installed.

Either point to the real source-code triggering the error (and provide a public data url), or go on to create a minimal self-contained reproducer (https://github.com/urllib3/urllib3/issues/3277#issuecomment-1890237079), again with public data.

(note that I stop monitoring the issue here, maintainers should comment at some point)

**Comment by henryjfry** [comment]
I cant find a public file I can reproduce the error wih, but its very definetly an error thrown by "_error_catcher" in Urllib3 with these specific Urls, i think its the header response.

A working header (eg https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4)

````
 HTTPHeaderDict({'Date': 'Sun, 14 Jan 2024 10:32:36 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '65536', 'Content-Range': 'bytes 990200-1055735/1055736', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'video/mp4'})
````

Versuse the RealDebrid response header contiaing the wrong "Content-Length"


````
HTTPHeaderDict({'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 381782703-381848239/381848239', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'})
````

**Comment by sigmavirus24** [comment]
I'm not at a computer so I can't attempt to reproduce any of this. I also don't use Kodi. One thought I have though is that the problem may lie in the request headers being sent, e.g., User Agent, and how the server responds based on that. If you can capture the request headers sent in each case that would be very helpful.

Also, make sure you redact the authorization header if it's present

**Comment by abebeos** [comment]
- potential cause: https://github.com/urllib3/urllib3/issues/3053

**Comment by sigmavirus24** [comment]
> I cant find a public file I can reproduce the error with, but its very definetly an error thrown by "_error_catcher" in Urllib3 with these problen Urls, i think its the header response.
> 
> A working header (eg https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4)
> 
> ````
>  HTTPHeaderDict({'Date': 'Sun, 14 Jan 2024 10:32:36 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '65536', 'Content-Range': 'bytes 990200-1055735/1055736', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'video/mp4'})
> ````
> 
> Versus the RealDebrid response header contiaing the wrong "Content-Length"
> 
> 
> ````
> HTTPHeaderDict({'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 381782703-381848239/381848239', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'})
> ````
> 
> The exact same code works on the command line and not in kodi because kodi is using a different version of urllib3.

What's interesting is if you do the math, -381782703+381848239 is 65536, not 65537.so it seems the server is sending the right range of bytes but claiming there's 1 more than reality. I'm guessing this is a server issue at this point.

IncompleteReads are a new exception in 2.0 but they're meant to warn about servers doing something wrong and it seems as though this one is.

**Comment by abebeos** [comment]
> do the math, -381782703+381848239 is 65536

@sigmavirus24 , you forgot +1, so its 65537

@sethmlarson , this is a non-issue, OP does neither provide a reproducer, nor a pointer to the real source code that causes the error, see https://github.com/urllib3/urllib3/issues/3277#issuecomment-1890830176

**Comment by henryjfry** [comment]
Ok its not a non issue but I think it is a math issue.

Content Range:
381782703-381848239/381848239

381848239-381782703 = 65536

The request if for 65536 bytes but:

381782703-381848239/381848239 = 381782702

And 

381848239-381782702 = 65537

Which I think is where the extra byte is coming from?

I can post the "HTTPHeaderDict" as per:
https://github.com/henryjfry/repository.thenewdiamond/issues/23

Unfortunately I am still unable to find a public URL to replicate this issue with but with RD URLS this is 100% reproducible.

**Comment by henryjfry** [comment]
So the working URL header from the commandline:

{'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '381926360', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'}

And the working code:

````
import struct, os
import urllib
__64k = 65536
__longlong_format_char = 'q'
__byte_size = struct.calcsize(__longlong_format_char)

def temp_file():
	import tempfile
	file = tempfile.NamedTemporaryFile()
	filename = file.name
	return filename

def is_local(_str):
	from urllib.parse import urlparse
	if os.path.exists(_str):
		return True
	elif urlparse(_str).scheme in ['','file']:
		return True
	return False

def hashFile_url(filepath): 
	#https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes
	#filehash = filesize + 64bit sum of the first and last 64k of the file
	name = filepath
	if is_local(filepath):
		local_file = True
	else:
		local_file = False
	if local_file == False:
		from urllib import request
		f = None
		#opener = None
		url = name
		request.urlcleanup()
		f = request.urlopen(url)
		filesize = int(f.headers['Content-Length'])
		if filesize < __64k * 2:
			try: filesize = int(str(f.headers['Content-Range']).split('/')[1])
			except: pass
		first_64kb = temp_file()
		last_64kb = temp_file()
		import requests
		headers = {"Range": 'bytes=0-%s' % (str(__64k))}
		r = requests.get(url, headers=headers)
		with open(first_64kb, 'wb') as f:
			for chunk in r.iter_content(chunk_size=1024): 
				if chunk: # filter out keep-alive new chunks
					f.write(chunk)
		if filesize > 0:
			headers = {"Range": 'bytes=%s-%s' % (filesize - __64k, filesize)}
		else:
			f.close()
			os.remove(first_64kb)
			return "SizeError" 
		try:
			r = requests.get(url, headers=headers)
			with open(last_64kb, 'wb') as f:
				for chunk in r.iter_content(chunk_size=1024): 
					if chunk: # filter out keep-alive new chunks
						f.write(chunk)
		except:
			f.close()
			if os.path.exists(last_64kb):
				os.remove(last_64kb)
			if os.path.exists(first_64kb):
				os.remove(first_64kb)
			return 'IOError'
		f = open(first_64kb, 'rb')
	try:
		longlongformat = '<q'  # little-endian long long
		bytesize = struct.calcsize(longlongformat) 
		if local_file:
			f = open(name, "rb") 
			filesize = os.path.getsize(name) 
		hash = filesize 
		if filesize < __64k * 2: 
			f.close()
			if local_file == False:
				os.remove(last_64kb)
				os.remove(first_64kb)
			return "SizeError" 
		range_value = __64k / __byte_size
		range_value = round(range_value)
		for x in range(range_value): 
			buffer = f.read(bytesize) 
			(l_value,)= struct.unpack(longlongformat, buffer)  
			hash += l_value 
			hash = hash & 0xFFFFFFFFFFFFFFFF #to remain as 64bit number  
		if local_file:
			f.seek(max(0,filesize-__64k),0) 
		else:
			f.close() 
			f = open(last_64kb, 'rb')
		for x in range(range_value): 
			buffer = f.read(bytesize) 
			(l_value,)= struct.unpack(longlongformat, buffer)  
			hash += l_value 
			hash = hash & 0xFFFFFFFFFFFFFFFF 
		f.close() 
		if local_file == False:
			os.remove(last_64kb)
			os.remove(first_64kb)
		returnedhash =  "%016x" % hash 
		return returnedhash
	except(IOError): 
		if local_file == False:
			os.remove(last_64kb)
			os.remove(first_64kb)
		return 'IOError'

````

**Comment by henryjfry** [comment]
I've created a python file I can import in kodi or run on the command line and will process the same two files and output their headers, before the first/last64kb request and at the last64kb.

So the code:

````
import struct, os
import urllib
__64k = 65536
__longlong_format_char = 'q'
__byte_size = struct.calcsize(__longlong_format_char)

try:
	import xbmc
except:
	pass

def temp_file():
	import tempfile
	file = tempfile.NamedTemporaryFile()
	filename = file.name
	return filename

def is_local(_str):
	from urllib.parse import urlparse
	if os.path.exists(_str):
		return True
	elif urlparse(_str).scheme in ['','file']:
		return True
	return False
	
def logger(msg):
	try: xbmc.log(str(msg)+'__MESSAGE__', level=xbmc.LOGINFO)
	except: print(str(msg))

def hashFile_url(filepath): 
	#https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes
	#filehash = filesize + 64bit sum of the first and last 64k of the file
	name = filepath
	if is_local(filepath):
		local_file = True
	else:
		local_file = False
	if local_file == False:
		from urllib import request
		f = None
		#opener = None
		url = name
		request.urlcleanup()
		f = request.urlopen(url)
		filesize = int(f.headers['Content-Length'])
		if filesize < __64k * 2:
			try: filesize = int(str(f.headers['Content-Range']).split('/')[1])
			except: pass
		first_64kb = temp_file()
		last_64kb = temp_file()
		import requests
		headers = {"Range": 'bytes=0-%s' % (str(__64k))}
		r = requests.get(url, headers=headers)
		logger(dict(r.headers))
		with open(first_64kb, 'wb') as f:
			for chunk in r.iter_content(chunk_size=1024): 
				if chunk: # filter out keep-alive new chunks
					f.write(chunk)
		if filesize > 0:
			headers = {"Range": 'bytes=%s-%s' % (filesize - __64k, filesize)}
		else:
			f.close()
			os.remove(first_64kb)
			return "SizeError" 
		try:
			r = requests.get(url, headers=headers)
			with open(last_64kb, 'wb') as f:
				for chunk in r.iter_content(chunk_size=1024): 
					if chunk: # filter out keep-alive new chunks
						f.write(chunk)
		except:
			f.close()
			if os.path.exists(last_64kb):
				os.remove(last_64kb)
			if os.path.exists(first_64kb):
				os.remove(first_64kb)
			return 'IOError'
		f = open(first_64kb, 'rb')
	try:
		longlongformat = '<q'  # little-endian long long
		bytesize = struct.calcsize(longlongformat) 
		if local_file:
			f = open(name, "rb") 
			filesize = os.path.getsize(name) 
		hash = filesize 
		if filesize < __64k * 2: 
			f.close()
			if local_file == False:
				os.remove(last_64kb)
				os.remove(first_64kb)
			return "SizeError" 
		range_value = __64k / __byte_size
		range_value = round(range_value)
		for x in range(range_value): 
			buffer = f.read(bytesize) 
			(l_value,)= struct.unpack(longlongformat, buffer)  
			hash += l_value 
			hash = hash & 0xFFFFFFFFFFFFFFFF #to remain as 64bit number  
		if local_file:
			f.seek(max(0,filesize-__64k),0) 
		else:
			f.close() 
			f = open(last_64kb, 'rb')

		for x in range(range_value): 
			buffer = f.read(bytesize) 
			(l_value,)= struct.unpack(longlongformat, buffer)  
			hash += l_value 
			hash = hash & 0xFFFFFFFFFFFFFFFF 
		f.close() 
		if local_file == False:
			os.remove(last_64kb)
			os.remove(first_64kb)
		returnedhash =  "%016x" % hash 
		return returnedhash
	except(IOError): 
		if local_file == False:
			os.remove(last_64kb)
			os.remove(first_64kb)
		return 'IOError'

from urllib import request
f = request.urlopen('https://20.download.real-debrid.com/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mp4')
logger(dict(f.headers))
f = request.urlopen('https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4')
logger(dict(f.headers))

logger('RealDebrid')

logger(hashFile_url('https://20.download.real-debrid.com/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mp4'))

logger('https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4')

logger(hashFile_url('https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4'))
````

On the commandline:

````
{'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '381926360', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'}

{'Date': 'Tue, 16 Jan 2024 09:45:06 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '1055736', 'Connection': 'close', 'Content-Type': 'video/mp4'}

RealDebrid

{'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 0-65536/381926360', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'}

698f18f7323fc01e

https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4

{'Date': 'Tue, 16 Jan 2024 09:45:08 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 0-65536/1055736', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'video/mp4'}

b3fbc599afa3b9fc
````

Output from kodi (trimmed to remove the extraneous log information):

````
{'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '381926360', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'}__MESSAGE__

{'Date': 'Tue, 16 Jan 2024 09:42:23 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '1055736', 'Connection': 'close', 'Content-Type': 'video/mp4'}__MESSAGE__

RealDebrid__MESSAGE__

{'Server': 'Lity 2.0', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 0-65536/381926360', 'Content-Disposition': 'attachment', 'Content-Type': 'application/force-download', 'Connection': 'close'}__MESSAGE__

 ('Connection broken: IncompleteRead(65536 bytes read, 1 more expected)', IncompleteRead(65536 bytes read, 1 more expected))===>A4K_Wrapper
IOError__MESSAGE__

https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4__MESSAGE__

{'Date': 'Tue, 16 Jan 2024 09:42:25 GMT', 'Server': 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.23', 'Last-Modified': 'Tue, 20 Oct 2020 10:54:05 GMT', 'ETag': '"101bf8-5b2180cb74c20"', 'Accept-Ranges': 'bytes', 'Content-Length': '65537', 'Content-Range': 'bytes 0-65536/1055736', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'video/mp4'}__MESSAGE__
b3fbc599afa3b9fc__MESSAGE__

````

**Comment by abebeos** [comment]
> Ok its not a non issue

It is a non-issue in context of this repo.

i replied in your repo

**Comment by abebeos** [comment]
Summary: you're requesting the wrong range, substract 1 and it should work:

`headers = {"Range": 'bytes=0-%s' % (str(__64k -1))}`
'headers = {"Range": 'bytes=%s-%s' % (filesize - __64k, filesize-1)}'

seems urllib3 2.x line warns, 1.x line does not warn.

@henryjfry , you can close this issue here now (and the one on kodi, too).

**Comment by henryjfry** [comment]
closed as per https://github.com/urllib3/urllib3/issues/3277#issuecomment-1893585214
