### ISSUE TITLE
Inconsistent Test Behaviour of 'HTTPConnection.default_socket_options'

### ISSUE THREAD

**Issue by abebeos** [urllib3/urllib3#3280]
### Subject

This came up during work on

- #2936 

The related PR is within

- https://github.com/urllib3/urllib3/pull/3278

This affects the `1.26.x` line.

### Environment

My usual dev env

```sh
>>> print("OS", platform.platform())
OS Windows-10-10.0.19041-SP0
>>> print("Python", platform.python_version())
Python 3.9.10
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 1.1.1m  14 Dec 2021
>>> print("urllib3", urllib3.__version__)
urllib3 1.26.18
```

### Steps to Reproduce

https://github.com/abebeos/urllib3/tree/2936-default-socket-options

get this version:

https://github.com/abebeos/urllib3/commit/05eb6805ae061599336b85aac69ff9b30011700a

```sh
# tests pass
nox --reuse-existing-virtualenvs --sessions test-3.9 -- -v -k TestHTTPProxyManager

# tests pass
nox --reuse-existing-virtualenvs --sessions test-3.9 -- -v -k TestConnectionPool

# tests pass (his contains both, TestHTTPProxyManager and TestConnectionPool)
nox --reuse-existing-virtualenvs --sessions test-3.9 -- -v test/with_dummyserver

# the full run will lead to 2failing tests (a 3rd one is date-related and not relevant)
nox --reuse-existing-virtualenvs --sessions test-3.9 -- -v
```

using pytest directly has the same behaviour.

### Expected Behavior

Full test run should work

### Actual Behavior

Full test run fails with 2 failures (but the tests pass in the partial runs)

```
[...]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_unicode_upload PASSED                                                                                [ 64%]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_nagle FAILED                                                                                         [ 64%]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_socket_options PASSED                                                                                [ 64%]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_disable_default_socket_options PASSED                                                                [ 64%]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_defaults_are_applied FAILED                                                                          [ 64%]
test/with_dummyserver/test_connectionpool.py::TestConnectionPool::test_connection_error_retries PASSED
[...]

Traceback (most recent call last):
  File "P:\work\urllib3\test\with_dummyserver\test_connectionpool.py", line 299, in test_nagle
    assert tcp_nodelay_setting
AssertionError: assert 0
__________________________________________________________________ TestConnectionPool.test_defaults_are_applied __________________________________________________________________
Traceback (most recent call last):
  File "P:\work\urllib3\test\with_dummyserver\test_connectionpool.py", line 352, in test_defaults_are_applied
    assert nagle_disabled
AssertionError: assert False
```

### Potential Cause

* test-system (e.g. dummyserver)?
* multithreading issue (parallel tests)?
* ?

**Comment by abebeos** [comment]
@sethmlarson , this is independent of #2936.

Seems like a bug within the overall test-system

**Comment by sigmavirus24** [comment]
These only became unstable as a result of the changes that weren't merged
