### ISSUE TITLE
SSL Certificate Verification Error when Downloading YouTube Video

### ISSUE THREAD

**Issue by AIWASS23** [urllib3/urllib3#3430]
### Subject
SSL Certificate Verification Error when Downloading YouTube Videos

### Environment

OS macOS-14.5-arm64-arm-64bit
Python 3.12.3
OpenSSL 3.0.13 30 Jan 2024
urllib3 2.2.1

### Steps to Reproduce

```py

import os
import pandas as pd
import numpy as np
from typing import List, Tuple

class YoutubeVideos:
    ''' 
    this class takes urls of videos found and creates a csv file with the urls and their respective classes.
    
    methods:
        create_csv(): make a csv file with the urls of the videos searched and their respective classes.
        get_urls(): return a list with the urls of the videos searched
        dowload_thumbnails(): make the download of the thumbnails of the videos searched.
        download_videos(): make the download of the videos searched.
        download_frames(): make the download of the frames of the videos searched.
    
    '''
    
    def __init__(self,  pacifier_text: str = 'real child using a pacifier in video', biting_nails_text: str = 'real child biting nails in video', thumb_sucking_text: str = 'real Child thumb sucking observation in video') -> None:
        '''
        Initializes the classes with the attributes of texts to be searched.
        
        Args:
            pacifier_text (str): Text to be searched in the classse chupeta no youtube.
            biting_nails_text (str): Text to be searched in the classe unha no youtube.
            thumb_sucking_text (str): Text to be searched in the classe dedo no youtube.
            
        '''
        self.pacifier_text = pacifier_text
        self.biting_nails_text = biting_nails_text
        self.thumb_sucking_text = thumb_sucking_text
        
        self.len_videos_pacifier = 0
        self.len_videos_biting_nails = 0
        self.len_videos_thumb_sucking = 0
    
    def get_urls(self) -> Tuple[List[str], List[str]]:
        ''' 
        Returns the urls of the videos and the urls of the thumbnails in a list using the VideosSearch
        
        Parameters:
            None
        
        Returns:
            urls_videos (list): lista com as urls dos vídeos.
            urls_thumbnails (list): lista com as urls das thumbnails(imagens) dos vídeos.
        '''
        videos_search_pacifier = VideosSearch(self.pacifier_text, limit=10)
        videos_pacifier = videos_search_pacifier.result()['result']
        
        videos_search_biting_nails = VideosSearch(self.biting_nails_text, limit = 10)
        videos_biting_nails = videos_search_biting_nails.result()['result']

        videos_search_thumb_sucking = VideosSearch(self.thumb_sucking_text, limit = 10)
        videos_thumb_sucking = videos_search_thumb_sucking.result()['result']

        videos = videos_pacifier + videos_biting_nails + videos_thumb_sucking
         
        urls_videos = []

        for video in videos:
            urls_videos.append(video['link'])
            
        urls_thumbnails = []

        for video in videos:
            urls_thumbnails.append(video['thumbnails'][0]['url'])
            
        self.len_videos_pacifier = len(videos_pacifier)
        self.len_videos_biting_nails = len(videos_biting_nails)
        self.len_videos_thumb_sucking = len(videos_thumb_sucking)
            
        return urls_videos, urls_thumbnails
    
    #real child using a pacifier in video -> 70% de aproveitamento com esse titulo contando thumbnails
    def create_csv(self, output_folder: str = 'urls_videos'):
        ''' 
        Creates a csv file with the urls of the videos searched and their respective classes,
        
        parameters:
            output_folder (str): Output folder to save the csv file.
            
        Returns:
            csv_file: Creates in the directory a csv file with the urls of the videos searched and their respective labels.
        
        Exemple csv: www.youtube.com/exemplo_chupeta, Chupeta
                      www.youtube.com/exemplo_unha, Unha
                      www.youtube.com/exemplo_dedo, Dedo
        '''
        
        urls_videos, _ = self.get_urls()
        
        os.makedirs(output_folder, exist_ok=True)
        
        csv_file_path = os.path.join(output_folder, 'ytb_vids_urls.csv')

        with open(csv_file_path, 'w', newline='') as csv_file:
            writer = csv.writer(csv_file)
            writer.writerow(['URL', 'LABEL']) 

            for i, url in enumerate(urls_videos):
                if i < self.len_videos_pacifier:
                    writer.writerow([url, 'chupeta'])
                elif i < self.len_videos_pacifier + self.len_videos_biting_nails:
                    writer.writerow([url, 'unha'])
                else:
                    writer.writerow([url, 'dedo'])
            
        csv_file.close()
        
                
    def download_videos(self,csv_file_path: str, output_folder: str = 'download_videos'):
        ''' 
        Makes the download of the videos searched.
            
        parameters:
            csv_file_path (str): Path to the csv file with the urls of the videos searched.
        Returns:
            downloads the videos of the videos searched.
        '''
        
        df = pd.read_csv(csv_file_path)
        urls = df['URL'].tolist()
    
        os.makedirs(output_folder, exist_ok=True)
        
        for url in urls: 
            try:                
                yt = YouTube(url)
                stream = yt.streams.get_highest_resolution()
                stream.download(output_path = output_folder)
            except Exception as e:
                print(f'Erro ao baixar o vídeo: {e}')
                
    def download_frames(self, csv_file_path: str, output_folder: str = 'frames_images', imgs_per_second: int = 1):
        """
        Captures as many images per second as is passed to the function

        parameters:
            csv_file_path (str): Path to the csv file with the urls of the videos searched.
            output_folder (str): Output folder to save the frames.

        Returns:
            Downloads the frames of the videos searched.
        """
        #
        os.makedirs(output_folder, exist_ok=True)
        
        df = pd.read_csv(csv_file_path)
        urls = df['URL'].tolist()
        
        for url in urls:
            yt = YouTube(url)
            stream = yt.streams.get_highest_resolution()
            stream_url = stream.url
            cap = cv2.VideoCapture(stream_url)

            if not cap.isOpened():
                print(f"Erro ao abrir o vídeo {url}")
                return

            fps = int(cap.get(cv2.CAP_PROP_FPS))
            frame_interval =  int(fps / imgs_per_second)  
            current_frame = 0
            frame_count = 0

            while True:
                ret, frame = cap.read()

                if not ret:
                    break

                if current_frame % frame_interval == 0:
                    frame_path = os.path.join(output_folder, f"frame_{frame_count}.png")
                    cv2.imwrite(frame_path, frame)
                    frame_count += 1

                current_frame += 1
            cap.release()
        
    def load_csv_video(self, csv_file_path: str, imgs_per_second: int = 1, vids: int = 2) -> Tuple[List[np.ndarray], List[np.ndarray]]:
        ''' 
        Loads the csv file with the urls of the videos searched and their respective classes.
        
        parameters:
            csv_file_path (str): Path to the csv file with the urls of the videos searched.
            imgs_per_second (int): Number of images per second to be captured.
            vids (int): Number of videos to be loaded.
            
        Returns:
            imgs (list): list with the images of the videos searched.
            labels (list): list with the classes of the videos searched.
        '''
        df = pd.read_csv(csv_file_path)
        urls = df['URL'].tolist()
        labels_df = df['LABEL'].tolist()
        
        urls = urls[:vids]
        labels_df = labels_df[:vids]

        imgs = []
        labels = []

        for url, label in zip(urls, labels_df):
            yt = YouTube(url)
            stream = yt.streams.get_highest_resolution()
            stream_url = stream.url
            cap = cv2.VideoCapture(stream_url)

            if not cap.isOpened():
                print(f"Erro ao abrir o vídeo {url}")
                return

            fps = int(cap.get(cv2.CAP_PROP_FPS))
            frame_interval = int(fps / imgs_per_second)
            current_frame = 0

            while True:
                ret, frame = cap.read()

                if not ret:
                    break

                if current_frame % frame_interval == 0:
                    imgs.append(frame)
                    labels.append(label)

                current_frame += 1

            cap.release()

        return np.array(imgs), np.array(labels)

```

### Error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

**Comment by sigmavirus24** [comment]
I don't see urllib3 in either the code sample or the stack trace. Instead I see the standard library. 

Please confirm that you're actually using urllib3 for this

**Comment by PythonCoderUnicorn** [comment]
i have same problem

my code: `youtube-dl "https://youtu.be/VxrKyDlZnKs" ` 

```
Loading video...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/pytube", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
                                                  ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, 
```
