### ISSUE TITLE
Certificate failed to validate for AWS S3 site

### ISSUE THREAD

**Issue by mmulich** [urllib3/urllib3#3465]
### Subject

The site `https://cs_sample_feed.s3.amazonaws.com/` when requested by urllib3 results in: `urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cs_sample_feed.s3.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cs_sample_feed.s3.amazonaws.com'. (_ssl.c:1007)")))`

### Environment

```
OS Linux-6.10.0-linuxkit-aarch64-with-glibc2.35
Python 3.10.12
OpenSSL 3.0.2 15 Mar 2022
urllib3 2.2.2
```

### Steps to Reproduce

```py
import urllib3
url = 'https://cs_sample_feed.s3.amazonaws.com/'
resp = urllib3.request('GET', url)
```

### Expected Behavior

The request should complete. All indications from various browsers and `openssl s_client -connect cs_sample_feed.s3.amazonaws.com:443` validate the certificates.

<details>
<summary>See also, output from curl</summary>

```
$ curl --verbose https://cs_sample_feed.s3.amazonaws.com > /dev/null
...snip...
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Apr 22 00:00:00 2024 GMT
*  expire date: Apr  7 23:59:59 2025 GMT
*  subjectAltName: host "cs_sample_feed.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
...snip...
```
</details>

### Actual Behavior

The code fails with `certificate verify failed: Hostname mismatch, certificate is not valid for 'cs_sample_feed.s3.amazonaws.com'.`. The _Common Name_ in the certificate is `*.s3.amazonaws.com`, so I fail to see the hostname mismatch issue.

<details>
<summary>Full traceback</summary>

```pytb
Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/app/env/lib/python3.10/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/app/env/lib/python3.10/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/app/env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/app/env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cs_sample_feed.s3.amazonaws.com'. (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cs_sample_feed.s3.amazonaws.com'. (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/env/lib/python3.10/site-packages/urllib3/__init__.py", line 193, in request
    return _DEFAULT_POOL.request(
  File "/app/env/lib/python3.10/site-packages/urllib3/_request_methods.py", line 136, in request
    return self.request_encode_url(
  File "/app/env/lib/python3.10/site-packages/urllib3/_request_methods.py", line 183, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/app/env/lib/python3.10/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/app/env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/app/env/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cs_sample_feed.s3.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cs_sample_feed.s3.amazonaws.com'. (_ssl.c:1007)")))
```

</details>

**Comment by graingert** [comment]
seems to be related to https://github.com/python/cpython/issues/103490

**Comment by keepworking** [comment]
It also relative with https://github.com/openssl/openssl/issues/12566

The underscore is available to domain name, but not available to host name

So, if you need to pass the host name verification then you can disable it on ssl context

example follows

```
import ssl
from urllib3 import PoolManager

context = ssl.create_default_context()
context.check_hostname = False

with PoolManager(ssl_context=context) as pool:
  pool.request('GET','https://cs_sample_feed.s3.amazonaws.com/')
```

**Comment by pquentin** [comment]
Disabling `check_hostname` isn't a good workaround here. Since we can't rely on OpenSSL to verify the hostname as it's not following the spec, you can use `assert_hostname` instead, which will use our own hostname checking implementation:

```python3
import urllib3

with urllib3.PoolManager(assert_hostname="cs_sample_feed.s3.amazonaws.com") as http:
    resp = http.request("GET", "https://cs_sample_feed.s3.amazonaws.com/")
    print(resp)
```

And next time you choose a bucket name, try to avoid underscores!

**Comment by sigmavirus24** [comment]
To be fair, openssl also enforces a limit on a DNS name in the list of SANs when generating a CSR. That limit is the defined max length of a common name but it does not apply in the specifications to SANs. So openssl applying validations that are invalid isn't strictly new or surprising.

**Comment by mmulich** [comment]
@pquentin Thank you for the workaround!

And for anyone else that might come across this from the `requests` API perspective. Here is a quick and dirty solution that incorporates this workaround.

```py
from requests.adapters import HTTPAdapter as BaseHTTPAdapter
from requests.sessions import Session as BaseSession
from urllib3.util import parse_url


class HTTPAdapter(BaseHTTPAdapter):
    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        _, _, host, _, _, _, _ = parse_url(request.url)
        # Re-initialize the PoolManager with the hostname assertion.
        # https://github.com/urllib3/urllib3/issues/3465#issuecomment-2324655893
        self.init_poolmanager(
             self._pool_connections,
             self._pool_maxsize,
             block=self._pool_block,
             assert_hostname=host,
         )
        return super().send(request, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)


class Session(BaseSession):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Override the base adapter to use our adapter
        self.mount('http://', HTTPAdapter())
        self.mount('https://', HTTPAdapter())
```
