### ISSUE TITLE
test failures on master

### ISSUE THREAD

**Issue by kevinburke** [urllib3/urllib3#454]
Running on a Mac, 10.9, with the following command

``` sh
while true; do make test ; if [[ $? -gt 0 ]]; then break; fi; done
```

Some of the failures are below.

ProtocolError not raised (got this one twice):

```
def test_source_address_error(self):
    for addr in INVALID_SOURCE_ADDRESSES:
        pool = HTTPConnectionPool(self.host, self.port,
                source_address=addr, retries=False)
        self.assertRaises(ProtocolError,
                pool.request, 'GET', '/source_address')
```

Not sure what r.data actually was:

``` python
FAIL: test_source_address (test.with_dummyserver.test_connectionpool.TestConnectionPool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevin/code/urllib3/test/with_dummyserver/test_connectionpool.py", line 598, in test_source_address
    assert r.data == b(addr[0])
AssertionError:
```

Connection failed:

``` python
ERROR: test_connection_read_timeout (test.with_dummyserver.test_socketlevel.TestSocketClosing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevin/code/urllib3/test/with_dummyserver/test_socketlevel.py", line 136, in test_connection_read_timeout
    self.assertRaises(ReadTimeoutError, pool.request, 'GET', '/')
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/Users/kevin/code/urllib3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/Users/kevin/code/urllib3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/Users/kevin/code/urllib3/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/Users/kevin/code/urllib3/urllib3/util/retry.py", line 223, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/kevin/code/urllib3/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/Users/kevin/code/urllib3/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/Users/kevin/code/urllib3/urllib3/connection.py", line 146, in connect
    conn = self._new_conn()
  File "/Users/kevin/code/urllib3/urllib3/connection.py", line 125, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/kevin/code/urllib3/urllib3/util/connection.py", line 87, in create_connection
    raise err
ProtocolError: ('Connection aborted.', error(61, 'Connection refused'))
-------------------- >> begin captured logging << --------------------
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
```

Another one

``` python
======================================================================
ERROR: test_timeout_errors_cause_retries (test.with_dummyserver.test_socketlevel.TestSocketClosing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kevin/code/urllib3/test/with_dummyserver/test_socketlevel.py", line 175, in test_timeout_errors_cause_retries
    response = pool.request('GET', '/', retries=1)
  File "/Users/kevin/code/urllib3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/Users/kevin/code/urllib3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/Users/kevin/code/urllib3/urllib3/connectionpool.py", line 579, in urlopen
    release_conn=release_conn, **response_kw)
  File "/Users/kevin/code/urllib3/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/Users/kevin/code/urllib3/urllib3/util/retry.py", line 265, in increment
    raise MaxRetryError(_pool, url, error)
MaxRetryError: HTTPConnectionPool(host='localhost', port=50350): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=50350): Read timed out. (read timeout=0.001)",))
```

The server from the same error

``` python
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/kevin/code/urllib3/dummyserver/server.py", line 70, in run
    self.server = self._start_server()
  File "/Users/kevin/code/urllib3/dummyserver/server.py", line 66, in _start_server
    self.socket_handler(sock)
  File "/Users/kevin/code/urllib3/test/with_dummyserver/test_socketlevel.py", line 145, in socket_handler
    sock = listener.accept()[0]
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
timeout: timed out
```

This is the result of running the tests maybe 100 times, while connected to a stable wifi network. Occasionally I also see `No handlers could be found for logger "tornado.access"`.
##

**Comment by sethmlarson** [comment]
This issue is probably outdated. Closing for now.
