### ISSUE TITLE
failures in tests in 1.10.3 under python2.7

### ISSUE THREAD

**Issue by idella** [urllib3/urllib3#621]
``` bash
======================================================================
ERROR: test_verified_with_bad_ca_certs (test.contrib.test_pyopenssl.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 93, in test_verified_with_bad_ca_certs
    https_pool.request('GET', '/')
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_verified_without_ca_certs (test.contrib.test_pyopenssl.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 106, in test_verified_without_ca_certs
    https_pool.request('GET', '/')
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
tornado.general: WARNING: SSL Error on 18 ('::1', 51276, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:581)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_discards_connection_on_sslerror (test.contrib.test_pyopenssl.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 409, in test_discards_connection_on_sslerror
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/usr/lib64/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
tornado.general: WARNING: SSL Error on 21 ('::1', 45956, 0, 0): [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:581)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_set_ssl_version_to_sslv3 (test.contrib.test_pyopenssl.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 397, in test_set_ssl_version_to_sslv3
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/usr/lib64/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
tornado.general: WARNING: SSL Error on 21 ('::1', 45957, 0, 0): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ssl_version_as_short_string (test.contrib.test_pyopenssl.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 405, in test_ssl_version_as_short_string
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/usr/lib64/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
tornado.general: WARNING: SSL Error on 21 ('::1', 45958, 0, 0): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ssl_version_as_string (test.contrib.test_pyopenssl.TestHTTPS_TLSv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 401, in test_ssl_version_as_string
    self.assertRaises(SSLError, self._pool.request, 'GET', '/')
  File "/usr/lib64/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
tornado.general: WARNING: SSL Error on 21 ('::1', 45959, 0, 0): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:581)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_hostname_in_first_request_packet (test.contrib.test_pyopenssl.TestSNI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_socketlevel.py", line 69, in test_hostname_in_first_request_packet
    pool.request('GET', '/', retries=0)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type SysCallError)
-------------------- >> begin captured logging << --------------------
urllib3.util.retry: DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=None)
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_verified (test.contrib.test_pyopenssl.TestHTTPS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/urllib3-1.10.3/work/urllib3-1.10.3/test/with_dummyserver/test_https.py", line 70, in test_verified
    self.assertFalse(warn.called, warn.call_args_list)
AssertionError: [call('Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)', <class 'urllib3.exceptions.SecurityWarning'>)]
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Starting new HTTPS connection (1): localhost
urllib3.connectionpool: INFO: Starting new HTTPS connection (2): localhost
urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 200 13

TOTAL                                  1767     98    94%   
----------------------------------------------------------------------
Ran 309 tests in 17.232s

FAILED (SKIP=4, errors=7, failures=1)
```

Do you require any further information?
##

**Comment by Lukasa** [comment]
This all looks like a problem with the way we handle PyOpenSSL.

**Comment by Lukasa** [comment]
Ok, I think the bug is in `urllib3.contrib.pyopenssl.ssl_wrap_socket`, specifically here:

```python
        except OpenSSL.SSL.Error as e:
            raise ssl.SSLError('bad handshake', e)
```

If I change it to this, most of the errors go away:

```python
        except OpenSSL.SSL.Error as e:
            raise ssl.SSLError('bad handshake: %r' % e)
```

That leaves only the `test_verified` failure.

**Comment by Lukasa** [comment]
The `test_verified` problem is a bit trickier, it seems to be in the code that handles parsing certs.

This time it's in `urllib3.contrib.pyopenssl.get_subj_alt_name`, specifically here:

```python
                if component.getName() != 'dNSName':
                    continue
```

In the case of the certificate being used in the tests, `component.getName()` is returning `rfc822Name`. This means we're concluding there's nothing in the SAN field. I don't really know off the top of my head whether that's valid or not: @t-8ch?

**Comment by Lukasa** [comment]
OpenSSL agrees with the PyOpenSSL code here, there's only one SAN field and it's email:

```
(py27)cory@corymbp:certs/ % openssl x509 -in server.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=FI, ST=dummy, L=dummy, O=dummy, OU=dummy, CN=SnakeOil/emailAddress=dummy@test.local
        Validity
            Not Before: Dec 22 07:58:40 2011 GMT
            Not After : Dec 18 07:58:40 2021 GMT
        Subject: C=FI, ST=dummy, L=dummy, O=dummy, OU=dummy, CN=localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (1024 bit)
                Modulus (1024 bit):
                    00:d7:7b:71:6a:98:25:af:3f:c5:cf:c6:ab:53:fb:
                    46:df:2f:54:ef:ce:f7:9b:8b:8e:a4:d1:62:1c:51:
                    5f:1b:3f:7b:f2:62:24:91:5c:6f:40:2e:6c:b3:64:
                    7e:06:1d:8f:54:56:ce:0e:10:39:02:30:33:81:49:
                    ec:c1:d3:2f:5a:8b:ff:5d:a1:33:5c:6a:27:2d:74:
                    40:6e:f2:77:dd:5c:aa:13:b7:3a:e7:f9:55:f8:50:
                    fa:e4:1f:98:66:ec:d4:35:7d:34:2e:8f:53:11:ef:
                    20:42:99:8a:8d:dd:0d:90:f8:47:ee:ba:3c:b1:d0:
                    5c:01:cc:0b:b2:d5:a2:98:bb
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Cert Type: 
                SSL Server
            Netscape Comment: 
                TinyCA Generated Certificate
            X509v3 Subject Key Identifier: 
                1B:E7:4A:E5:4A:2C:D3:C4:14:C0:05:A8:7C:36:F7:6B:C6:1C:62:52
            X509v3 Authority Key Identifier: 
                keyid:19:77:7F:23:62:62:42:59:45:FB:75:9D:C7:73:72:04:BB:33:0A:2D
                DirName:/C=FI/ST=dummy/L=dummy/O=dummy/OU=dummy/CN=SnakeOil/emailAddress=dummy@test.local
                serial:B3:EB:B1:CA:2F:E1:BF:E3

            X509v3 Issuer Alternative Name: 
                <EMPTY>

            X509v3 Subject Alternative Name: 
                email:root@localhost
    Signature Algorithm: sha1WithRSAEncryption
        57:75:e7:46:5c:72:cf:98:e5:41:78:a5:a3:4e:66:9e:91:c6:
        90:8b:8e:2c:9e:16:2a:13:5b:97:46:82:10:5d:0b:32:c3:e6:
        1a:e7:e9:ff:b9:1c:4f:29:93:bf:0b:bf:04:11:22:f4:f2:b9:
        cb:4d:d6:57:9b:81:81:63:21:d8:98:cc:b4:01:d5:91:ef:2d:
        37:d2:f8:8e:cc:09:16:59:14:51:6e:e7:9c:b1:a5:33:14:22:
        3e:17:d8:d3:57:92:c7:b9:1c:f3:57:c7:d4:2b:08:84:13:db:
        30:ce:45:a0:32:97:d5:4c:f1:6e:3e:0c:f1:c0:6f:60:31:ba:
        c1:7e

```

So I think our code is technically right, but we're having a disagreement with what the stdlib does.

**Comment by Lukasa** [comment]
Ok, our code is not right, because it doesn't match the stdlib. I chunked a `print cert.get('subjectAltName', ())` into the connection code and then forced that test to fail in PyOpenSSL and stdlib mode. Here's the output from PyOpenSSL:

```
-------------------- >> begin captured stdout << ---------------------
[]

--------------------- >> end captured stdout << ----------------------
```

And from the stdlib:

```-------------------- >> begin captured stdout << ---------------------
(('email', 'root@localhost'),)

--------------------- >> end captured stdout << ----------------------
```

So I think that either we need to enhance our PyOpenSSL function to produce the same output as the stdlib, or we need to make the warning check smarter (to also warn on the certificate in the stdlib case), or maybe both.

**Comment by t-8ch** [comment]
@Lukasa I think `get_subj_alt_name` should return *all* SANs. `match_hostname` will filter them anyways.
However we have to map the names: 'dNSName' -> 'DNS', the email stuff etc.

**Comment by Lukasa** [comment]
@t-8ch Cool, that seems clear enough. That's the only outstanding problem, #622 fixes the other stuff.

**Comment by idella** [comment]
thx for the quick reply. You have just the 1
FAIL: test_verified (test.contrib.test_pyopenssl.TestHTTPS)
to finalise right?

**Comment by Lukasa** [comment]
Correct.

**Comment by sethmlarson** [comment]
I believe this is fixed now. Let me know if that's not the case.
